### ISSUE TITLE
Merge Boxes

### ISSUE THREAD

**Issue by hdesalvo** [DrCoffey/DeepSqueak#101]
When selecting multiple audio files in the multidetect function, I get the following error:

`Warning: Upper Range Above Samplng Frequency
Unrecognized function or variable 'h'.

Error in merge_boxes (line 47)
if ~any(Accepted); close(h); return; end

Error in SqueakDetect (line 175)
Calls = merge_boxes(AllBoxes, AllScores, AllClass, AllPowers, audio_info, 1, score_cuttoff, 0);

Error in multinetdect_Callback (line 77)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 31)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0) 
Error while evaluating UIControl Callback.'

Using MATLABR2020a.

**Comment by hdesalvo** [comment]
This occurs when doing a single audio file as well. It was working fine for me earlier. Not sure what happened.

**Comment by DrCoffey** [comment]
This one is easier, the upper frequency range in the detection settings must be less than half the sample rate for the audio file. So if you sample at 192 kHZ, you can go higher than 96 kHz in the spectrogram/detection settings.
