### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by likith012** [DrCoffey/DeepSqueak#102]
Is the dataset made public for further improvements?

**Comment by DrCoffey** [comment]
Hey, I emailed you. Unless this is a different person lol, then let me know.

**Comment by likith012** [comment]
> Hey, I emailed you. Unless this is a different person lol, then let me know.

@DrCoffey Can you send the dataset link to this mail address `likith012@gmail.com`

**Comment by DrCoffey** [comment]
Did you want the mouse or rat training data?

**Comment by likith012** [comment]
> Did you want the mouse or rat training data?
@DrCoffey Got access to the mouse v2 data, can you also send me the rat data too. Thanks in advance.
