### ISSUE TITLE
Background gain

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#104]
Hi Dr. Coffey, 

I've been working with deepsqueak for several studies now. I really like the program. One problem that I constantly run into is that the background "gain" is too dark. I end up having to draw a box around nothing so I can better see the signal. Is there a way to set the gain so that it doesn't auto to the detected signal? I attached pictures to illustrate the issue. 

<img width="355" alt="dark deepsqueak" src="https://user-images.githubusercontent.com/45463545/112005688-ff9a0480-8af0-11eb-95a4-fe035265567d.PNG">
<img width="211" alt="redraw for gain" src="https://user-images.githubusercontent.com/45463545/112005712-032d8b80-8af1-11eb-8d74-219b23d14d6a.PNG">

**Comment by DrCoffey** [comment]
Hey, we have a new test build that has this, and **many** more features built in. I will be updating the main branch sometime soon, but I would recommend checking it out now, it is pretty stable.
 
https://github.com/DrCoffey/DeepSqueak/tree/Screener

**Comment by cmlenell1** [comment]
Great! Thank you!

Charlie
Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by cmlenell1** [comment]
Hi Dr. Coffey,

I used the new version of deepsqueak and I love the changes. Being able to
add USVs and change the detection box of calls that were cut off were much
needed functions.

I was wondering if you wanted to add "peak frequency" to the measurements
and excel export like I suggested on a previous thread. The Cuicci Lab and
other researchers like Wohr use peak frequency a lot. I managed to add the
code and I think it would help make this amazing program more widely
adopted and utilized. Let me know if you want my code again.

Thanks again!

Charlie



Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
Hey Charlie, I completely missed this. Ya, send me the code and I will add peak frequency to the default outputs!

**Comment by cmlenell1** [comment]
Okay. Let me know if you have any questions. Pasted the code below.

Add these three lines to the "CalculateStats.m" underneath
% Power of the call contour
stats.Power = ridgePower;

% Peak frequency of the call contour
stats.RidgeFreq = FreqScale*stats.ridgeFreq_smooth + Box(2);
stats.PeakFreq = stats.RidgeFreq(stats.Power==max(ridgePower));

Then add peak frequency to "excel_Callback.m" by changing the following
lines

exceltable = [{'ID'} {'Label'} {'Accepted'} {'Score'} {'Begin Time (s)'}
{'End Time (s)'} {'Call Length (s)'} {'Principal Frequency (kHz)'} {'Low
Freq (kHz)'} {'High Freq (kHz)'} {'Delta Freq (kHz)'} {'Frequency Standard
Deviation (kHz)'} {'Slope (kHz/s)'} {'Sinuosity'} {'Mean Power (dB/Hz)'}
{'Tonality'} {'Peak Freq'}];

exceltable = [exceltable; {ID} {Label} {accepted} {Score} {stats.BeginTime}
{stats.EndTime} {stats.DeltaTime} {stats.PrincipalFreq} {stats.LowFreq}
{stats.HighFreq} {stats.DeltaFreq} {stats.stdev} {stats.Slope}
{stats.Sinuosity} {stats.MaxPower} {stats.SignalToNoise} {stats.PeakFreq}];



Best,


Charlie
Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
Thanks for this!

**Comment by cmlenell1** [comment]
Hi Dr. Coffey,

I've been using this version and was wondering if you were planning on
including a delete button to delete detected noise elements and was also
wondering why the contour of this version of deepsqueak had such much fewer
points than the previous version.

Thanks!

Charlie
Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
Hey Charlie,

You can remove any call by right clicking on it. You can also remove all rejected calls with Tools->Automatic Review->Remove Rejected Calls.

The contour is based on the tonality slider, but I don't think we changed the code or point calculation in the new version. Can you give a specific example?

-Kevin

**Comment by DrCoffey** [comment]
Hey Charlie,

There doe seem to be something up with the contour extraction. I will investigate and get back to you.

-Kevin

**Comment by cmlenell1** [comment]
Yes, Sorry for the delay. When you change the display overlap percentage
(in display range), the contour and value changes as well.

Best,

Charlie

Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
Ya, the contour points are based on the number of pixels in the display. I am working on the edge detection this week, so there may be a couple code updates that improve contour detection.
