### ISSUE TITLE
Error in Detecting Calls for All Short Calls Network

### ISSUE THREAD

**Issue by slahmed** [DrCoffey/DeepSqueak#108]
Hello! I'm using DeepSqueak on Matlab 2019a and I've been having a bit of an issue analyzing my USV audio files. I used DeepSqueak in February with similar audio files (same sampling frequency, recorded from the same audio chamber) and had no issues using the All Short Calls Network. Now I am getting large errors. This is what comes up when I try to detect any calls:

Error in Network, Skiping Audio Chunk
Warning: Error using fasterRCNNObjectDetector/parseDetectInputs (line 740)
Expected I to be nonempty.

Error in fasterRCNNObjectDetector/detect (line 462)
            params = this.parseDetectInputs(I, varargin{:});

Error in SqueakDetect (line 120)
            [bboxes, scores, Class] = detect(network, im2uint8(im),
            'ExecutionEnvironment','auto','NumStrongestRegions',Inf);

Error in multinetdect_Callback (line 77)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0) 
> In SqueakDetect (line 168)
  In multinetdect_Callback (line 77)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0)

I noticed that someone else here had a similar issue, so I tried to use the comments to fix this. I tried running DeepSqueak on two separate computers with higher graphics cards than the one I am using, but no success. I also tried changing the parameters and had no success there. I was, however, able to detect calls using the Short Rat Call Network. Any help would be greatly appreciated!

**Comment by DrCoffey** [comment]
Hey slahmed,

DeepSqueak has issues on a few versions of MATLAB due to Mathworks making changes to Deep Learning functions, I think that is whats happening here. That said, I highly recommend you update to 2020b and download DeepSqueak V3 here:

https://github.com/DrCoffey/DeepSqueak/tree/Screener

We have made major upgrades and will be merging it with the main branch soon. It is vastly improved and has a lot of new features:

    Simplified Detection Settings
    Brand New YOLO V2 based Detection Architechture
    Navigate Entire Audio Files to Quickly & Easily Refine Detections or Add New Boxes
    Retrain Existing Networks With Your Own Recordings
    Start From Scratch: Hand Box Calls and Train a New Species Detector
    Contour Invarient Clustering With Variational Auto Encoders

**Comment by DrCoffey** [comment]
I will no longer be supporting V2.6 issues, so I am going to close this issue. If you have any issues with V3, please start a new issue.
