### ISSUE TITLE
Plotting t-SNE of detected calls: Add legend with labeled colorbar and change plot background

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#109]
Hey there,

thanks again for creating this super useful tool! :)

Currently I am looking at several DeepSqueak - detected calls and want to plot them with your t-SNE functionality. The output is a very beautiful .jpg file. 
Is there a way to add a labeled colorbar to the t-SNE plot and to additionally change the background of the plot to a transparent or white background?

Thanks in advance!

Best,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

I'm not sure if I have mentioned this to you yet, but we have a new version of DeepSqueak in development that has **major upgrades**. We are going to merge with the main branch soon. You can download it and test out all the new feature here: 

https://github.com/DrCoffey/DeepSqueak/tree/Screener

For your question, the image is created from line 153-190 in create_tsne_Callback.m

It should be possible to add a colorbar with the frequency range or the labels, but for some reason we didn't include that. Russell marx coded this and I am not sure how exactly it all works. I don't have time to dig into it all now, but if you figure it out please share the code! 

You can at least display the min and max freq by adding disp(minfreq); and disp(maxfreq); anywhere after they are generated.

I'll put this on the development list, but I'm not sure when I can get to it.

-Kevin

**Comment by DrCoffey** [comment]
Hey Isa,

I am going to consider this a "Feature Request" and move it to the Gitter: https://gitter.im/DeepSqueak_Community/FeatureRequests

V3 is now available on the main branch, so give it a shot and start a new issue if you find any.

-Kevin
