### ISSUE TITLE
Trouble running newest version of Deepsqueak

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#11]
I'm trying to run the new version of Deepsqueak and I'm getting the following error with no detections.

Warning: Error in Network, Skiping Audio Chunk 
> In SqueakDetect (line 115)
  In multinetdect_Callback (line 93)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
'Threshold' is not a recognized parameter. For a list of valid name-value pair arguments, see the documentation for this function.

**Comment by DrCoffey** [comment]
hey cmlenell1,

The threshold input to the detect function doesn't work in 2017. It's fixed, just re-download DeepSqueak!

-Kevin
