### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by lund1807** [DrCoffey/DeepSqueak#111]
Hello! I have just started using this program and I am still learning how to use it exactly. Is there a way that I can add additional calls? Sometimes the program groups together two calls and I want to know if I can split them up. I was also wondering if there was a way in which I could somehow get it to look for both long and short calls at the same time? When using the short call network it tends to cut the larger calls into multiple fragments, but using the long call network groups small calls together. Please let me know!

**Comment by DrCoffey** [comment]
Hey,

There is a new version of DeepSqueak we are working on that can do all of this. It is available for download here:

https://github.com/DrCoffey/DeepSqueak/tree/Screener

You need to update to MATLAB 2020a or later.

Add new boxes with the draw button or the by hitting "d" 

You can also adjust all of the boxes and see the entire audio file. 

Finally, if you use the "multidetect" button you can choose as many networks as you want. DeepSqueak will merge all of the detections. You can also detect each separately and merge the files after with the merge tool.

**Comment by lund1807** [comment]
![Screenshot 2021-06-17 152226](https://user-images.githubusercontent.com/85753887/122467203-dd911080-cf7f-11eb-9ce5-21a39f9a29e5.png)
Hello again! The problem above was solved, but now I am running into another issue. Whenever I try to run classification of my calls, I get this error. It had worked the past couple days but now I'm not sure why it has stared doing this. Please let me know what I can do. Thank you!

**Comment by DrCoffey** [comment]
Are you using 2.6 or 3.0? 

The supervised classifiers from 2.6 don't work in 3.0, so that may be it. I need to work on supervised classification in 3.0, but it has been low on my priority list because we don't use it anymore. We prefer to use entirely unsupervised clustering since we don't actually know what the true call categories are.

**Comment by lund1807** [comment]
I am using 2.6. Is there any other reason it wouldn't be working? Or is there a way to take what the unclassified output gives and assign classifications to them?

**Comment by DrCoffey** [comment]
The error makes me think the issue is with an individual call/box. I wonder if your first or last call is too close to the beginning or end of the file, so the code can't pad the image. Try removing the first or last call and running it again.

FYI, soon I will be upgrading the main branch to 3.0 and I will likely stop supporting the older version.

**Comment by lund1807** [comment]
Hi DrCoffey, 

This might be a stupid question but I can't seem to figure it out. What does the score mean in the Excel output? Also, what does the mean power tell us and why is it negative? I'm trying to figure out how to analyze the data but I am getting confused on what information would be the most useful.

**Comment by DrCoffey** [comment]
Score is just the probability value the neural network places on each detection being a true call. So how likely is the object detected a USV, according to the network. Anything under .5 is auto rejected.

Mean power is just the loudness of the call. It is measured in dB/Hz which is logarithmic. Log values between 0 and 1 are negative. Practically speaking larger numbers are louder. Generally I caution against analyzing loudness unless you can control the animals location relative to the microphone, as an animals farther away or facing another direction may sound quieter. Also if you have more than 1 microphone the gain needs to be perfectly calibrated to compare. If you use 1 mic and a small box and have big differences in loudness, you might be able to tease out real differences.
