### ISSUE TITLE
V3 download

### ISSUE THREAD

**Issue by ngnae** [DrCoffey/DeepSqueak#112]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DrCoffey** [comment]
Hey ngnae,

V3 is available here: https://github.com/DrCoffey/DeepSqueak/tree/Screener

It is currently on a separate tree for development purposes, but it will be merged with the main branch soon.\

-Kevin
