### ISSUE TITLE
Version 2.6.2 not available for download?

### ISSUE THREAD

**Issue by hahmhannah** [DrCoffey/DeepSqueak#115]
Hello, I have downloaded version 2.6.1 from the sidebar of the 'code' page. It says that 2.6.1 is the latest release, but upon opening the software, there is a message saying there is version 2.6.2. When I click the link to take me to the download, I am sent to the same page with 2.6.1 as the latest release. Is there a page I'm missing? Thanks

**Comment by DrCoffey** [comment]
He hahmhannah,

A release is just a stable version, but not the most recent. You can download 2.6.2 from the green code button on the main page.

That said, a brand new version is going to be released in a few days.

you can get the development version here: https://github.com/DrCoffey/DeepSqueak/tree/Screener

but the stable V3 release will be on the main page very soon.

-Kevin
