### ISSUE TITLE
DeepSqueak v3 Testing

### ISSUE THREAD

**Issue by DrCoffey** [DrCoffey/DeepSqueak#126]
- [ ] Test general workflow
- [ ] Test unsupervised clustering & clustering GUI
- [ ] Test supervised classification
- [ ] Test manual detection review
- [ ] Test training a new detection network

**Comment by MxMarx** [comment]
MATLAB has stuff for making an [automated testing framework](https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html), is this worth using?
