### ISSUE TITLE
Error in CalculateStats

### ISSUE THREAD

**Issue by Melissa-Salazar** [DrCoffey/DeepSqueak#131]
Hi Dr. Coffey,

I just downloaded and installed DeepSqueak and I've tried to use it but every time I hit a key or try to accept or reject a call I get an error message in the command box. I am also not getting the data/graphs that appear on the left side of the window. I don't really have any background in coding so I'm not too sure what I should do to fix this error. I assume it might be an easy fix. I have the MatLab 2021a installed and am using the most recent verison of DeepSqueak. I also installed all of the toolboxes and have checked multiple times that they are installed. 

Thank you,
Melissa
[matlab-ds error.pdf](https://github.com/DrCoffey/DeepSqueak/files/7132301/matlab-ds.error.pdf)
![Matlab-ds error (1)](https://user-images.githubusercontent.com/90331761/132598847-2a441fed-77c7-4a3a-90a4-f01fe6ae93c2.png)

**Comment by DrCoffey** [comment]
Hey @Melissa-Salazar. Try deleting your settings.mat file from the main folder and loading DeepSqueak again. I changed some of the contour extraction methodology and the settings file needs to be built from scratch.

**Comment by DrCoffey** [comment]
@Melissa-Salazar, There was also another error I just caught, so you should also pull the latest version.

**Comment by Melissa-Salazar** [comment]
@DrCoffey, yes that solved the issue! Thank you!
