### ISSUE TITLE
warning for 'CheckpointPath' and error in merge_boxes

### ISSUE THREAD

**Issue by mbreach** [DrCoffey/DeepSqueak#135]
Hello wonderful DS developers,

I am using DeepSqueak V3 on the latest version of Matlab R2021a. When I type "DeepSqueak" everything loads okay. The GUI pops up appropriately and I am able to initiate call detection.  But once call detection is initiated, I get the following warning:

Warning: While loading an object of class 'nnet.cnn.TrainingOptionsSGDM':
The value of 'CheckpointPath' is invalid. Checkpoint path must be a char array and an existing directory with write permission. 
> In multinetdect_Callback (line 77)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
Unrecognized function or variable 'h'.

Then the box with detection speed and the number of call fragments pops up and starts to load. However, the call detection doesn't finish and I get the following error:

Error in merge_boxes (line 45)
if ~any(Accepted); close(h); return; end

Error in SqueakDetect (line 143)
Calls = merge_boxes(AllBoxes, AllScores, AllClass, audio_info, 1, score_cuttoff, 0);

Error in multinetdect_Callback (line 80)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
 
Error while evaluating UIControl Callback.

As a result, no detection call file is made. 

I closed everything out and tried again, and the 'CheckpointPath' warning popped up again after I initiated detection, but the error on merge boxes did not. However, this time it told me that no calls were found. (I know calls are there, because I've run this file on a previous version of DS before and plenty of calls were detected)

Your help is extremely appreciated!

**Comment by DrCoffey** [comment]
Hey @mbreach , the checkpoint warning is not an issue. It exists because I trained the networks on my computer and the checkpoint path doesn't exist on other computers. Unfortunately, I can't edit that value in the networks directly so the warning will always be displayed.

Did you make sure to change the detection network to the rat or mouse short call network to detect the file? I think the rat long call network populates first. I should probably change that sometime.

If that isn't the issue would you mind sharing the audio file so I can take a closer look?

-Kevin

**Comment by mbreach** [comment]
Hi Kevin,

I have tried both the long and short rat calls networks because I wondered if that had something to do with it. I just tried it again using the short rat network and got the same error, but realized I didn't paste the first line of the error in my original post:

Unrecognized function or variable 'h'.

Error in merge_boxes (line 45)
if ~any(Accepted); close(h); return; end

Error in SqueakDetect (line 143)
Calls = merge_boxes(AllBoxes, AllScores, AllClass, audio_info, 1, score_cuttoff, 0);

Error in multinetdect_Callback (line 80)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
 
Error while evaluating UIControl Callback.

I will upload the audio file to drive and post it here shortly.

**Comment by mbreach** [comment]
Here is the audio file: https://drive.google.com/file/d/1u19gnrKYu92TY_41W0fSzPj0pub_toMH/view?usp=sharing

**Comment by DrCoffey** [comment]
Hey @mbreach. I was able to detect the file you sent successfully. I would try to download the newest version of DeepSqueak and try again from scratch (Delete your old settings file if you update with Github Desktop). Are you using a Mac or PC

[USV1 2021-09-17  1_09 PM.zip](https://github.com/DrCoffey/DeepSqueak/files/7198602/USV1.2021-09-17.1_09.PM.zip)
?

**Comment by mbreach** [comment]
Hi Kevin,

That’s weird, I haven’t messed with the settings at all since I downloaded DS. But That definitely worked. Thanks so much for your time!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DrCoffey** [comment]
No problem!
