### ISSUE TITLE
Harmonics

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#144]
Hi Dr. Coffey,

We have analyzed USVs with both SASLab Pro and Deepsqueak and bandwidth (delta frequency) is different between the two programs. One advantage using SASLab Pro is that it measures harmonics of the call. Is it possible for Deepsqueak to measure harmonics?
Charlie Lenell (Ciucci Lab-UW Madison)

<img width="181" alt="Harmonic USV" src="https://user-images.githubusercontent.com/45463545/143090680-e8554458-78c8-4c6e-9992-fb8144b468c2.PNG">

**Comment by DrCoffey** [comment]
Hey Charlie,

DeepSqueak uses the call contour to calculate the stats, and it can't have 2 contours at the same time sample so harmonics are excluded.

You could extract the total frequency range from the Bounding Box Height, that info is in the detection file, but you would need to write a quick script to extract it.

I have always been worried that harmonics are artifacts of our microphones because USVs are such loud tonal noises, but I haven't tried to confirm that.

**Comment by cmlenell1** [comment]
Thanks for the prompt response!

Where is the bounding box height calculated? I'm having trouble finding it
in the functions codes.

Charlie



Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
The "Box" is saved in the calls variable. I think it is created in SqueakDetect.m

If you drag any detection file into your workspace you can open the calls variable to see the Box variable for each call.

It is a 4 value array  [start time(S)  low frequency(kHz) box width(s)  frequency height(kHz)]

So the last number in "Box" is the total frequency bandwidth of the box.

![CallCap](https://user-images.githubusercontent.com/39605011/143139957-8f02ecd1-17cb-42e3-a38c-693c2063e222.JPG)

**Comment by cmlenell1** [comment]
Thanks again for your speedy reply! I'll try to figure out how to extract
that from a folder of the mat files.
Best,
Charlie

Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by cmlenell1** [comment]
I'm trying to figure out how to get the CalculateStats.m file to calculate
the bandwidth. I'm not finding the line of code needed for this in the
SqueakDetect.m file.

Does this look right?

% Frequency Range of the call contour
stats.FreqRange = range(stats.ridgeFreq)

Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
Hey, sorry I forgot to respond to this question. Did you ever figure out what you were looking for?

**Comment by cmlenell1** [comment]
That's okay. No, I was never able to figure out how to measure bandwidth
Bounding Box Height automatically.
Charlie

Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
This one is actually pretty simple.

Replace the following 2 files in your version of DeepSqueak and the excel files will include Box bandwidth in the final column.

I had to zip them to upload to github.

[functions.zip](https://github.com/DrCoffey/DeepSqueak/files/7998972/functions.zip)
