### ISSUE TITLE
Display range

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#145]
I'm analyzing mouse usvs and some go above 125kHz but I can't extend the range beyond 125. Any suggestions? Thanks! -Charlie

**Comment by DrCoffey** [comment]
Hey Charlie, If you set the display range above 0.5x the sample rate DeepSqueak will just use 0.5x the sample rate as the high frequency cutoff. So if you record at 250kHz, the highest frequencies you can record and visualize is 125kHz. If you want to go higher than 125 you will need to record at a higher sample rate. 

https://en.wikipedia.org/wiki/Nyquist_frequency

**Comment by cmlenell1** [comment]
Is there a way to adjust this .5x setting so that I can view higher
frequencies with the current sampling rate?
Charlie
Charles Lenell, PhD, CCC-SLP
*he/they*

**Comment by DrCoffey** [comment]
Unfortunately it is not a limitation of DeepSqueak, but a mathematical limitation. When you convert a continuous function or signal (the audio pressure wave) into a discrete sequence (microphone samples) you can only detect frequencies at 0.5x the sample rate. If the wave frequency is higher than that it will just be missed by the discrete samples of the microphone, so the frequency info above 125kHz isn't present in the 250kHz sampled recording. More info in the wiki link.

**Comment by cmlenell1** [comment]
Thanks for clarifying!
Charles Lenell, PhD, CCC-SLP
*he/they*
