### ISSUE TITLE
training detection network

### ISSUE THREAD

**Issue by ROAbb** [DrCoffey/DeepSqueak#149]
**Describe the bug**
I am trying to train the Deepsqueak detection network on my data. But, to make sure my work is correct, I first used the test data (Example Mouse Recording.flac) in the Deepsqueak directory. Since Deepsqueak requires a data detection file to train the detection network, I used the existing detection network for detecting USVs in this file. Then I generated images using parameters nfft=0.0022, overlapping=0.0016, window length=0.0032 to create the image, which resulted in 100 images. Then, using these images and without using the previous networks, I trained the detection network. Finally, using this network, with default detection settings and high recall, it detected 566 segments, but almost all of them are noise. 
This also applies to my own files, only noise is detected by the network. Is the problem with the fft parameters or how to train the network or the MATLAB version used?

**To Reproduce**
Unfortunately, Github does not support attaching .mat files. The audio file is already in the DeepSqueak directory.

**Expected behavior**
I expect around 650 segments to be detected by the new model.

**Additional context** 
I am using version 1.0 of Deepsqueak on MATLAB 2020a.

Thank you in advance for your time

**Comment by DrCoffey** [comment]
Hey ROAbb, Are you using the most up-to-date version of DeepSqueak v3? 

Available here: https://github.com/DrCoffey/DeepSqueak

**Comment by ROAbb** [comment]
Hey DrCoffey,

When I use the new version (v3) to load the detection from the previous version or v3 (which I used "Mouse Detector Yolo R2.mat" for the detection), I get the following error:

`Error using images.roi.Rectangle/set
Unrecognized property LabelAlpha for class Rectangle.

Error in images.roi.internal.ROI/parseInputs

Error in images.roi.Rectangle

Error in drawrectangle (line 190)
h = images.roi.Rectangle(varargin{:});

Error in render_call_boxes (line 57)
            handles.FocusWindowRectangles{box_number} = drawrectangle(...

Error in update_fig (line 56)
handles = render_call_boxes(handles.focusWindow, handles, true,false);

Error in initialize_display (line 99)
update_fig(hObject, eventdata, handles);

Error in loadcalls_Callback (line 52)
initialize_display(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.`

**Also, even though the calls are loaded, I can not move on them and get the following error:**

`Reference to non-existent field 'spect'.

Error in update_focus_display (line 10)
set(handles.spect,'CData',s_f,'XData', ti_f,'YData',fr_f/1000);

Error in update_fig (line 46)
handles = update_focus_display(handles);

Error in mousePositionSelection_Callback (line 15)
update_fig(hObject, eventdata, handles);

Error in initialize_display>@(hObject,eventdata)mousePositionSelection_Callback(hObject,eventdata,guidata(hObject)) (line 73)
set(handles.epochSpect,'ButtonDownFcn', @(hObject,eventdata) mousePositionSelection_Callback(hObject,eventdata,guidata(hObject)));
 
Error while evaluating Image ButtonDownFcn.`

**Comment by ROAbb** [comment]
Dear @DrCoffey 
Thanks for your suggestion. 
Upgrading my MATLAB to 2021 and using DeepSqueak v3 solved the problem of network training.
Now I have another question regarding training the detection network. could you please take care of it?

On the one hand, we know that the Yolo network has a large number of parameters, and on the other hand, it takes so much time to provide a large number of corrected segments for the network input. Given these issues, what is the minimum number of segments required for network training (To provide a usv detection model with good performance)?

**Comment by DrCoffey** [comment]
We have had good luck training networks with any where from several hundred to several thousand training images.

The key to a goo training set isn't really raw number, but good representation of the call types you want to detect. I try to include a roughly equal number of each type of call, and a good distribution of call variance (loud, quiet, with background noise, without, etc.). I also often include training boxes that just surround call segments, like boxing each part of a step-down call separately. 

Unfortunately I haven't found some magic number of calls that always works, you just need to test out some different training sets and see what works best. Good luck!

**Comment by ROAbb** [comment]
Thank you for your guidance.
