### ISSUE TITLE
My DeepSqueak can‘t  exactly export excel file

### ISSUE THREAD

**Issue by Durling** [DrCoffey/DeepSqueak#151]
**Describe the bug**
Deer Dr. Coffey, when I choose the "Export Excel Log (Call Statistics)",  DeepSqueak produce a blank excel file. And I have  confirmed that the Detected Call File have accepted calls. I detect calls again, choose the new detected file to export, it still produce a blank excel file. 

**To [Reproduce**]
With the attached audio/detection files:
1. Go to 'File'
2. Click on 'Import/Export'
3. Scroll down to 'Export Excel Log (Call Statistics)'
4. See error: 'warnning: Call box start beyond audio duration.  '

**Expected behavior**
Since I needed to check the detection, I passed the audio file and part of the project file to a colleague for him to review and give me the updated file. I found that the files I passed back could not be loaded and could not be exported to excel with the content, so I re-detected them and found the same situation.

**Additional context** 
Windows 10  /  MATLAB 2021b / DeepSqueak V3

**Comment by Durling** [comment]
Duplicate of #

**Comment by DrCoffey** [comment]
Hey @Durling 

Can you successfully output a Call Statistics file for one of the example detection files?

-Kevin
