### ISSUE TITLE
Supervised classification

### ISSUE THREAD

**Issue by scoki211** [DrCoffey/DeepSqueak#152]
Hi Kevin and colleagues

I am trying out DS v3, having used 2.0 and 2.5 the past couple of years to great success. Love all the new additions. However, one thing I can't see in this version is the classifiers that came stock with previous versions of DS. It seems all the interface functionality for supervised classification is there, so I pulled the Wright classifier mat file (which we used for supervised classification in our previous research) from v2.5 and tried to use them in v3. I am getting the following errors when I do so:

```
Error using DAGNetwork/classify (line 193)
Incorrect input size. The input images must have a size of [200 100 1].

Error in SeriesNetwork/classify (line 577)
            [labels, scores] = this.UnderlyingDAGNetwork.classify(X, varargin{:});

Error in SupervisedClassification_Callback (line 38)
    [Cl, sc] = classify(net.ClassifyNet, X);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('SupervisedClassification_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.
```

Are these Wright classifier mat files used on previous versions of Deepsqueak completely incompatible with V3? Is there any way to make them compatible, or would we have to train something from scratch?

Kind regards
Jack Scott (PhD candidate)

**Comment by DrCoffey** [comment]
Hey Jack,

Unfortunately the old classifiers don't work with v3. We were never really happy with the accuracy of supervised classifiers and pretty much only use unsupervised clustering now.

If you choose to train a new network and get good results feel free to share them here:
https://gitter.im/DeepSqueak_Community/NetworkTraining

I believe some others are already posted there if you want to try them out.

-Kevin
