### ISSUE TITLE
Unsupervised Clustering; using two different detection files

### ISSUE THREAD

**Issue by vjoshi48** [DrCoffey/DeepSqueak#158]
Hello,

I am writing because I am trying to create an unsupervised clustering model using two different detection files. The issue is that one of the detection files has a column called "power" and one of the files does not. 

When I go into the detection file that has the column called "power", I tried to simply delete the power column and save the file as such. The problem is, is that when I do this modification of deleting the power column, I get this error for the file: 

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('UnsupervisedClustering_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

Unrecognized field name "SampleRate".

Error in CreateFocusSpectrogram (line 55)
rate = audioReader.audiodata.SampleRate;

Error in CreateClusteringData (line 118)
    [I,wind,noverlap,nfft,rate,box,~,~,~,~,pow] = CreateFocusSpectrogram(Calls(i,:), handles, true,
    p.Results.spectrogramOptions, audioReader);

Error in UnsupervisedClustering_Callback (line 25)
                            [ClusteringData, ~, ~, ~, spectrogramOptions] =
                            CreateClusteringData(handles, 'forClustering', true, 'save_data', true);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('UnsupervisedClustering_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

I know very little about matlab, but it appears that the file type is changing whenever I modify this column. Let me know if there is a way to use these two detection files for unsupervised clustering correctly. 

Thank you,

Varun Joshi

**Comment by DrCoffey** [comment]
Hey Varun,

It sounds like you have detection files from different version of DeepSqueak. There was a lot of active development a few months ago, and not everything is back compatible, though I thought we solved the issues around the power column.

The error you sent actually appears to relate to the "SampleRate" variable not existing. 

Can you cluster using the example detection files and were the files you are using detected on the most up-to-date version of DeepSqueak?

-Kevin

**Comment by vjoshi48** [comment]
I was able to resolve the issue. I realized that when I deleted the power column, this resulted in the file's samplerate parameter not being accessible (however, the parameter was still there when I opened the file to check). I updated matlab and this seemed to resolve the error; there was some incompatibility or bug that I was running into with matlab itself! 

Thank you,

Varun Joshi
