### ISSUE TITLE
Issue with loading calls

### ISSUE THREAD

**Issue by taylorkimball123** [DrCoffey/DeepSqueak#162]
Hello! I am not sure if this is related to where I have my audio files, but I am having issues when loading calls after detecting calls. It will detect the calls, but then I am unable to see them. I have tried troubleshooting, but cannot seem to figure this out so I figured I'd ask here. Here is what is happening:

Warning: While loading an object of class 'nnet.cnn.TrainingOptionsSGDM':
The value of 'CheckpointPath' is invalid. Checkpoint path must be a char array and an existing
directory with write permission. 
> In multinetdect_Callback (line 77)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
659 Calls found in: Pair5_Exp1Day9_03-02-22 
Unrecognized field name "current_file_id".

Error in loadcalls_Callback (line 15)
        [tmpcalls, ~] =
        loadCallfile(fullfile(handles.detectionfiles(handles.current_file_id).folder,
        handles.current_detection_file), handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by DrCoffey** [comment]
Hey @taylorkimball123. Can you load the included example call files?

**Comment by taylorkimball123** [comment]
> Hey @taylorkimball123. Can you load the included example call files?

Hello! I can load the example file, but can't load either .flac or .wav files I have in the same folder.

**Comment by DrCoffey** [comment]
I would try turning DeepSqueak off and on, then resetting the detection and audio folders with File->Select Audio Folder, etc. Then select the detection file from the drop-down menu and hit load calls.

There is also a recently updated version of DeepSqueak that is available, so you might consider upgrading and seeing if that fixes things.
