### ISSUE TITLE
USV rat DeepSqueak Matlab

### ISSUE THREAD

**Issue by Neurolabrat** [DrCoffey/DeepSqueak#167]
Hi,

I'm recording USVs from adult rats with DeepSqueak 

I get the following errors: 

Warning: While loading an object of class 'nnet.cnn.TrainingOptionsSGDM':
The value of 'CheckpointPath' is invalid. Checkpoint path must be an existing directory with write permission or empty.
> In multinetdect_Callback (line 77)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
Unrecognized function or variable 'h'.

Error in merge_boxes (line 45)
if ~any(Accepted); close(h); return; end

Error in SqueakDetect (line 143)
Calls = merge_boxes(AllBoxes, AllScores, AllClass, audio_info, 1, score_cuttoff, 0);

Error in multinetdect_Callback (line 80)
        Calls = [Calls; SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
 
Error while evaluating UIControl Callback.

>> 

All toolboxes are installed and everything is loading in to the assigned folder so I really don't know where I go wrong here. Anybody has a guess? 

Thank you in advance!

**Comment by DrCoffey** [comment]
Hey @Neurolabrat 

The warning is nothing but this error is strange: Unrecognized function or variable 'h'.

'h' is referring to the progress bar window. Is that not opening for you when you run detections? Do you have any special circumstances, like are you using a Mac?

**Comment by DrCoffey** [comment]
Hey @Neurolabrat I found the bug that causes this error. It is fixed if you update. Basically if Deepsqueak found calls, but none passed the score threshold things were breaking
