### ISSUE TITLE
Increasing/changing the frequency range that supervised classification images are generated in

### ISSUE THREAD

**Issue by vjoshi48** [DrCoffey/DeepSqueak#169]
When looking at the supervised classification code, it appears that the frequency range for which the calls are trained is fixed to be from 15KHz to 75KHz: "Rejected Calls are ignored. This function produces training images from 15 to 75 KHz, and with width of the box."

This may already be an existing feature, but how do I increase this range? I am training on rat pup calls which are well above the 75KHz upper threshold most of the time. I would be okay with having a window that is 60KHz big, but I would like to be able to move the window up. How can I do this? 

Thank you in advance.

**Comment by DrCoffey** [comment]
Hey @vjoshi48. DeepSqueak V3 uses CreateClusteringData.m to generate images. It should create images with a fixed frequency range from the 5th to 95th percentile of all boxes in the dataset.

Line 82:
else
         freqRange(1) = prctile(Calls.Box(:,2), 5);
         freqRange(2) = prctile(Calls.Box(:,4) + Calls.Box(:,2), 95);
end

Can you explain where 15-75 is coming from?

**Comment by vjoshi48** [comment]
My apologies, the 15-75 was coming from one of the comments in the code. The comment was the one quoted in the initial post. I am not too familiar with matlab, so I did not catch this. Thank you for your prompt reply!
