### ISSUE TITLE
Intensity Measure and binary classifier

### ISSUE THREAD

**Issue by cmlenell1** [DrCoffey/DeepSqueak#17]
Hi Dr. Coffey,

We use a intensity-calibrated signal during recording. I was wondering how max power is calculated and if a DB measure can be extracted or calculated from this measure. 

Also, wondering if the acoustic output can be used to automatically distinguish simple from unmodulated USVs. 

Thanks!

Charlie

**Comment by MxMarx** [comment]
I've updated the code so max power is now calculated as power spectral density (dB/Hz), which what the "spectrogram" command outputs. Before, if was just amplitude. 

We included a k-means classification gui in the unsupervised classification menu, which uses the shape, frequency and duration of the contour. Using a small number (3,4) for k might distinguish between simple and modulated calls.

Some of the variables in the excel output, particularly frequency standard deviation, would probably discriminate between simple and modulated calls, but I haven't tried this yet.

**Comment by VoiceScientist** [comment]
Thanks for the info and update. Is the new power spectral density calculation the maximum value at a single point in each USV? If so, would it be possible to also output the mean power spectral density of the entire detected call? Our lab is interested in comparing not just frequency components but also the intensity of vocalizations between groups of animals and in different conditions. Having different ways of calculating the intensity would be helpful.
Aaron

**Comment by MxMarx** [comment]
I switched the column name to "Mean Power (dB/Hz)" in the excel output. The value is the mean power along the call contour.
The value will probably be sensitive to the contour threshold, but it should be reliable as long as the whole call is picked up for both quiet and loud calls.
Tonality might also be a useful metric for comparing the intensity of vocalizations.
