### ISSUE TITLE
Question about view cluster function

### ISSUE THREAD

**Issue by Fiuza-J** [DrCoffey/DeepSqueak#170]
Hello Dr. Coffey, 

I am using DeepSqueak on rat USVs recordings. I performed unsupervised clustering and excluded several calls from the clusters because DeepSqueak was identifying noise as USVs. After this, I updated the detection files with the new clusters, and then I tried the view clusters function again to double-check if everything was ok and correct the remaining clusters (I have quite a few calls in each cluster so I've decided not to do this all at once). However, I get the impression that DeepSqueak reallocated the calls after I excluded the first batch of calls that were actually noise. Is this supposed to happen? 
I tried to look for info about this in the wiki but couldn't find anything about it.. 

Additionally, when doing the clustering, MATLAB plots an image of the best call for each cluster, but with the removal of the calls that were actually noise, I suppose that this would also change, is it possible to generate another figure with the revised clusters? 

Thank you in advance. 

Best regards, 
Juliana

**Comment by DrCoffey** [comment]
Hey Juliana, 

If you save the cluster labels and then use View Clusters, they should end up in the same cluster. If you are only viewing a subset they may be in a different order. I believe the calls are sorted by centrality to the cluster, so if you remove some calls the order will change. 

I don't believe removing noise would change the call closest to the center of the cluster unless that call was noise itself. If you want, you can re-cluster everything after deleting the rejected calls, that would likely change the overall clustering.

**Comment by DrCoffey** [comment]
On second look, I think It has to do with rejected calls. I am working on a fix now.

**Comment by DrCoffey** [comment]
Hey Juliana,

I think the issue is fixed. Update and try clustering/viewing again.
