### ISSUE TITLE
Supervised Classifier not Running

### ISSUE THREAD

**Issue by babywing** [DrCoffey/DeepSqueak#171]
Hi Dr. Coffey! I recently downloaded MATLAB & DeepSqueak to our shared lab computer (we've been running DS on our personal computers  but decided to also have it on a shared desktop). We have a custom supervised classifier that we use on our mouse .wav files. It runs perfectly fine on our personal computers, but for some reason it is not running on our shared PC. We have all of the required MATLAB packages installed. I tried both the original program and the update. We select supervised classifier > choose our classifier > select detection file to run classifer on. The program "loads file" but stops before running the classifier.  Here is the error message we receive after running the supervised classifier:
`Dot indexing is not supported for variables of this type.

Error in SupervisedClassification_Callback (line 29)
wind=options.spectrogram.windowsize;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('SupervisedClassification_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.`

Thank you for your help!

**Comment by DrCoffey** [comment]
Hey @babywing, this is fixed in the new update. Sorry about that.
