### ISSUE TITLE
Detection network taining 

### ISSUE THREAD

**Issue by Fiuza-J** [DrCoffey/DeepSqueak#172]
Hello Dr. Coffey,  

I am trying to optimize call detection using the Rat Detector YOLO V1 network in my rat USV recordings. 
I was trying to use detection files from a previous dataset where I manually drew all the call boxes to generate the call images and then train the network with those. I have 118 detection files and I've selected all of them but when it is creating images it stops in the 15th file. I tried to do this twice and the result was the same. I don't get any error message in MATLAB (the second time I just got warnings, but I assume it is because MATLAB had to overwrite the previous files). 

![image](https://user-images.githubusercontent.com/106884295/173362683-b77e4ff2-20ee-4a84-a787-72d5a094f096.png)

Is there a limit of detection files to be used for this feature or is there something that I am missing? 
Thank you in advance for your time. 

Best, 
Juliana

**Comment by DrCoffey** [comment]
Hey @Fiuza-J that is very strange. There should not be a limit on detection files, I'll look into it.

**Comment by DrCoffey** [comment]
Are your detection file names very similar? It looks like it is trying to write them to the same directory?

**Comment by Fiuza-J** [comment]
Hey DrCoffey, 

Yes, actually, part of the name overlaps between files. Here are some of them: 

![image](https://user-images.githubusercontent.com/106884295/173449813-94b27f75-326c-4578-987a-51084ee0dc01.png)

**Comment by Fiuza-J** [comment]
Hey @DrCoffey, 

Just checking if you have already had some time to look into this. 
Thank you again for your help! 

Best, 
Juliana

**Comment by DrCoffey** [comment]
Hey @Fiuza-J Sorry for the slow reply, things have been crazy at lab and DeepSqueak is on the back burner.

I just tested a 20 file run and got through them all. Perhaps something is wrong with the 15th file in your set. Have you tried just removing that 1 file? Also, please update DeepSqueak there were a couple bug fixes recently

**Comment by DrCoffey** [comment]
Hey @RaphaelField and @Fiuza-J  , I just pushed a major update with a lot of bug fixes. Try downloading the new version, and make sure you are using a recent release of MATLAB (2021a or later). Let me know if that fixes your problem.
