### ISSUE TITLE
Performance tweaking multi detect

### ISSUE THREAD

**Issue by BerendWijers** [DrCoffey/DeepSqueak#176]
**Is your feature request related to a problem? Please describe.**
According to the [documentation](https://documentation.help/DeepSqueak/documentation.pdf) we could, in previous versions of DeepSqueak, adjust the chunk length for analysis to tweak performance. This option seemingly has disappeared. I have a suspicion that DeepSqueak might not be set to use the full GPU. Therefore, I would like to be able to adjust these settings as only a small portion of my GPU is being used whereas I would aim to use the GPU to its fullest capacity. See additional information for performance results during runtime. I verified that Matlab is using the GPU by using `nvidia-smi` to determine which processes are running on the GPU. 

**Describe the solution you'd like**
Return the option to set performance settings such as analysis chunk length and other options if applicable.

**Describe alternatives you've considered**
I've changed the function detect call arguments to force MEX code generation and force GPU environment, which provided no additional performance gain.
`
[bboxes, scores, Class] = detect(network, im2uint8(im), 'ExecutionEnvironment','gpu','SelectStrongest',1,'Acceleration','mex'); % added explicit GPU and mex Accel.
`

**Additional context**
The hardware / software I run DeepSqueak with:

Software:
* Windows Server 2019
* Matlab R2021a, Update 7
  * MATLAB support for MinGW-w64  C/C++ compiler
  * GPU Coder interface for deep learning libraries
  * Statistics and Machine Learning Toolbox
  * Signal Processing Toolbox
  * Parallel Computing Toolbox
  * Image Processing Toolbox
  * Deep Learning Toolbox
  * Curve Fitting Toolbox
  * Computer Vision Toolbox
* DeepSqueak v3.04
* NVIDIA driver version 516.31

Hardware:
* Virtual Machine
  * CPU: Intel Xeon Gold 6342 2.80 GHz, 11 cores
  * RAM: 88 GB 
  * GPU: [NVIDIA A10 Tensor Core GPU ](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a10/pdf/a10-datasheet.pdf)

**Files**
[https://filesender.surf.nl/?s=download&token=721de2d1-e231-4ee9-988f-7d372cc77f73](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffilesender.surf.nl%2F%3Fs%3Ddownload%26token%3D721de2d1-e231-4ee9-988f-7d372cc77f73&data=05%7C01%7CB.C.Wijers%40uva.nl%7Ccca17e1d61c7414228d708da73da4e0d%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637949678680738997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9lUKCA8SKCZ1aqiaJ4JPyduZL8cygyXg4UVW5PA%2BW8E%3D&reserved=0)

**Monitoring (snapshot) of GPU usage during DeepSqueak run with audio file 1.** 
![deepsqueak_3 0 4_A10_gpu_usage](https://user-images.githubusercontent.com/7668550/182198301-d9fe6baa-bc8d-4974-9ee9-07633c7771f4.png)

**Comment by DrCoffey** [comment]
Hey @BerendWijers, I removed the chunk length option because it was causing detection variability. The Yolo networks are trained using a set image size, so I now detect at that size. When you train a network you can use bigger images, and then the detection will use bigger images. The included networks all use 0.5s images, and so that is the chunk length. I was trying to optimize for detection quality, not speed.

**Comment by BerendWijers** [comment]
Hi @DrCoffey , Thank you for the answer! Very understandable choice to remove chunk length option then. 

I will relay the information to the group I'm working with. Furthermore, I will try and determine if we still require a performance increase. If that is the case I will look more in the direction of the pipeline design rather than trying to (performance) optimize DeepSqueak itself as that is not possible.
