### ISSUE TITLE
In multidetect merging boxes fails and produces an error. 

### ISSUE THREAD

**Issue by BerendWijers** [DrCoffey/DeepSqueak#177]
Hi Dr. Coffey,

I'm assisting a Postdoc and her Master Student in the setup of an analysis pipeline, using Deep Squeak. I've run into a technical issue and I'm hoping you can help me resolve it. I've provided a description below. Thank you in advance!

**Describe the bug**
When using Multi-detect, after the first audio file has been analysed the merging boxes step fails and produces an error causing the GUI to hang on 'Merging boxes..'

The error message is:

```
Unrecognized function or variable 'h'.

Error in merge_boxes (line 45)
if ~any(Accepted); close(h); return; end

Error in SqueakDetect (line 143)
Calls = merge_boxes(AllBoxes, AllScores, AllClass, audio_info, 1, score_cuttoff, 0);

Error in multinetdect_Callback (line 80)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0)
 
Error while evaluating UIControl Callback.
```

**To Reproduce**
With the attached audio/detection files:
1. In the main windows go to 'multidetect'
2. Select files 1-4 (attached)
3. Set settings for both networks:
  * Networks: Long Rat Detector Yolo R1 and Rat Detector Yolo R1
  * Total Analysis Length: 0
  * Frequency Cut-off High: 90
  * Frequency Cut-off Low: 18
  * Score Threshold: 0.7
  * Append data to filename: 1 
5. Wait for the first audio file to be processed
6. See error in MATLAB console

**Expected behavior**
I expect merging boxes step to resolve and the detection to continue with the next file(s). 

**Additional context** 
Before this error, a warning is issued:

During the 'Loading network' step, this warning is issued.

```
Warning: While loading an object of class 'nnet.cnn.TrainingOptionsSGDM':
The value of 'CheckpointPath' is invalid. Checkpoint path must be a char array and an existing directory
with write permission. 
> In multinetdect_Callback (line 77)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0) 

```

Software:
* Windows Server 2019
* Matlab R2021a, Update 7
  * MATLAB support for MinGW-w64  C/C++ compiler
  * GPU Coder interface for deep learning libraries
  * Statistics and Machine Learning Toolbox
  * Signal Processing Toolbox
  * Parallel Computing Toolbox
  * Image Processing Toolbox
  * Deep Learning Toolbox
  * Curve Fitting Toolbox
  * Computer Vision Toolbox
* DeepSqueak v3.04
* NVIDIA driver version 516.31

Hardware:
* Virtual Machine
  * CPU: Intel Xeon Gold 6342 2.80 GHz, 11 cores
  * RAM: 88 GB 
  * GPU: [NVIDIA A10 Tensor Core GPU ](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a10/pdf/a10-datasheet.pdf)

**Files**
[https://filesender.surf.nl/?s=download&token=721de2d1-e231-4ee9-988f-7d372cc77f73](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffilesender.surf.nl%2F%3Fs%3Ddownload%26token%3D721de2d1-e231-4ee9-988f-7d372cc77f73&data=05%7C01%7CB.C.Wijers%40uva.nl%7Ccca17e1d61c7414228d708da73da4e0d%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637949678680738997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9lUKCA8SKCZ1aqiaJ4JPyduZL8cygyXg4UVW5PA%2BW8E%3D&reserved=0)

**Comment by DrCoffey** [comment]
Hey @BerendWijers 

This crash happened because the long network found a few calls but none of them passed the 0.7 score threshold, and DeepSqueak got confused. I fixed the bug, and it should run fine now if you update DeepSqueak.
