### ISSUE TITLE
Can't load in detection files or classify on one computer

### ISSUE THREAD

**Issue by babywing** [DrCoffey/DeepSqueak#178]
Hi Kevin, 

One of my students is having an issue loading in detection files and classifying them. She has the newest update of MatLab, all packages installed, and version 3.0.4 . She selects the detection file and corresponding audio file, clicks load calls, hears the "error" sound, and her GUI looks weird (the deepsqueak logo flips upside down). I have the same version of MatLab and version 3.0.4, and I have no issues loading calls, detecting files, and classifying them. We both use Mac laptops. Thanks for the help!

**Comment by DrCoffey** [comment]
Hey @babywing I would need to see the complete error message to help.

-Kevin
