### ISSUE TITLE
Spectrogram resolution adjustment feature request

### ISSUE THREAD

**Issue by Hobart10** [DrCoffey/DeepSqueak#181]
Dear Dr. Coffey,
Sometimes I'll manually check the call type based on the spectrogram, but the relatively low resolution makes some panels too blurred to recognize in my usage. May I ask how could I modify the resolution in focus window?
Thank you!

**Comment by DrCoffey** [comment]
Hey @Hobart10. The spectrogram settings are in the "display settings" on the bottom right of the main window.  The auto feature should get you ideal settings, but you can change them manually as well.

**Comment by Hobart10** [comment]
Ahhh! Thank you! Sorry I didn't notice that option.
