### ISSUE TITLE
Can't train supervised classifier

### ISSUE THREAD

**Issue by babywing** [DrCoffey/DeepSqueak#183]
Hi Dr. Coffey, 

I'm trying to create a new/updated supervised classifier, but I cannot load any detection files and get this error message in the console. The "loading files x/xx" window pops up, but I get an error sound, and the files cease to load. I have an existing supervised classifier I created earlier this year, so I'm not sure why I cannot create a new one using the latest version. Thanks!! 
![Screen Shot 2022-10-17 at 4 05 50 PM](https://user-images.githubusercontent.com/90716227/196273633-5eb5c839-f2bf-4685-81c1-31930328c49f.jpg)

**Comment by DrCoffey** [comment]
Hey @babywing. It looks like DeepSqueak can't find the audio file. Try setting both the detection & audio folder and then restarting deepsqueak. Make sure you can load one of the detection files, and then try training the classifier.

I just tested some supervised training/classification on my data and it was working fine.

**Comment by babywing** [comment]
Thank you! I selected the audio folder that accompanies the detection file folder, and it seems to be working.
