### ISSUE TITLE
Need Khz grids

### ISSUE THREAD

**Issue by dnarvaiz** [DrCoffey/DeepSqueak#186]
In some call type classification schemes, call types are determined by overall shape within a set of parameters determined by khz. For example, in [Scattoni et al's](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2972364/) classification scheme, an "upward-modulated call" exhibits a continuous increase in frequency that is ≥12.5 kHz, with a terminal dominant frequency at least 6.25 kHz more than the frequency at the beginning of the vocalization. When supervising these classifications, it is not possible to determine if these criteria are being met because the khz markers on the x axis are too wide and distant from the calls. Could you please add an option of including grid marks so that we may determine the shape of the calls as measured by khz? It would also be helpful to add aa ruler or indicator on the box that surrounds the calls so that one may tell how many khz's the shape of the box is. Thank you!

**Comment by DrCoffey** [comment]
Hey @dnarvaiz 

I will probably not be able to get around to this request for the foreseeable future, but if you are able to make the modification to the code I would be happy to add it via a pull request. Unfortunately I have very little time for development and have a big list of goals above this. Also, we are really moving away from categorizing calls based on experimenter derived rigid rules, and are instead focused on unsupervised categorization methods.

If you really need this data, you can already pull out information about the change in frequency (total not continuous) and the box size from the exported excel log. _File-Export-Excel Log_
