### ISSUE TITLE
Unable to load or detect calls

### ISSUE THREAD

**Issue by rszelaya** [DrCoffey/DeepSqueak#187]
Hi, I am having trouble detect calls. I do have all the add ons necessary for deepsqueak to work. It won't do anything besides show this error and stuck on the initializing window.

------------------------------------------------------------------------------------------
Unrecognized field name "detector".

Error in SqueakDetect (line 14)
network=networkfile.detector;

Error in multinetdect_Callback (line 80)
        Calls = [Calls; SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
 
Error while evaluating UIControl Callback.

**Additional context** 
Operating system / MATLAB R2022b

**Comment by DrCoffey** [comment]
Hey, I'm not exactly sure what is going on here. First, try to set the network, audio, and detections folders in the file menu. Set all the defaults and see if you can load or detect calls using all the included files.

You may also try deleting the settings file and reopening deepsqueak. It will build a new default settings file, which sometimes foxes things.

**Comment by connorjohnson1** [comment]
I'm having the exact same issue. It worked the first few times I loaded audio but I can no longer load any audio, including the example recordings. Also I don't see a settings file, where could I find that?

**Comment by DrCoffey** [comment]
@connorjohnson1 The settings file is in the main DeepSqueak directory

**Comment by DrCoffey** [comment]
Hey @connorjohnson1 and @rszelaya  , I just pushed a major update with a lot of bug fixes. Try downloading the new version, and make sure you are using a recent release of MATLAB (2021a or later). Let me know if that fixes your problem.
