### ISSUE TITLE
Unable to Navigate with the Buttons

### ISSUE THREAD

**Issue by SujitVankineni** [DrCoffey/DeepSqueak#188]
Hi, 

On DeepSqueak, I was able to load my calls and play them. However I am unable to navigate using the arrow buttons to move one call, focus window, or one page window. 

I was hoping you could help me and see what I am doing wrong. 

I am using MATLAB version 2020a and I am getting this error code. 

![Screenshot 2023-02-15 122323](https://user-images.githubusercontent.com/125495485/219118933-78c0a69d-849b-46b0-96c1-af2feadbf420.png)

Any help will be appreciated!

Thank You

**Comment by DrCoffey** [comment]
Hey @SujitVankineni. This is strange, it looks like Deep squeak doesn't think the spectrogram is loaded (if you can see calls it should be loaded). I would make sure you have the newest version on DeepSqueak (3.0.4) and then try to delete the settings file in the main directory before loading DeepSqueak (it will create a fresh one).

**Comment by DrCoffey** [comment]
Hey @SujitVankineni , I just pushed a major update with a lot of bug fixes. Try downloading the new version, and make sure you are using a recent release of MATLAB (2021a or later). Let me know if that fixes your problem.
