### ISSUE TITLE
harmonics + parameters for K means clustering 

### ISSUE THREAD

**Issue by bmacagno** [DrCoffey/DeepSqueak#193]
Hi Dr. Coffey and Dr. Marx,

My first question has to do with detecting harmonics. I was going through the closed issues and saw Dr. Coffey previously mentioned that harmonics are excluded from DeepSqueak #144 . Does this mean that unsupervised clustering is unable to take into account the presence of harmonics when grouping calls, and is only based off the features of the main call contour?

To the DeepSqueak community, 
I am an undergrad finishing up a maternal separation USV project, and I am trying to figure out the best way to weigh the K-means clustering parameters, as well as how to best optimize the clusters. If anyone is willing to share how they weighed the parameters and if they used elbow optimization or a user defined number of clusters I would really appreciate it! 

I feel like I am a bit in over my head and short on time to train a supervised classifier, even though that would be preferred. If anyone has trained a supervised classifier for **mouse pup USVs** and has advice (or would be willing to share their network...) I would be extremely grateful! 

Bea Macagno
Department of Psychology
Western Washington University

**Comment by DrCoffey** [comment]
Hey @bmacagno. The newest version of DeepSqueak can perform clustering on the entire spectrogram inside the box (Using VAEs), so would account for harmonics. This would be a good thing to bring up in the Discussions group: https://github.com/DrCoffey/DeepSqueak/discussions
