### ISSUE TITLE
Rate and RelBox are missing

### ISSUE THREAD

**Issue by billylau12** [DrCoffey/DeepSqueak#197]
Hi!
In the older versions of DeepSqueak (v2.6 and older), all detection files have the first column for 'Rate' and 3rd column for 'RelBox'. However, in the newest version of DeepSqueak (v3.1), these columns are missing in the detection files.  Please advice on how to get these columns back into the detection files.

Thank you,
Billy

**Comment by DrCoffey** [comment]
Hey @billylau12 The new detection files are structured very differently than 2.6, and we can't add that info back. I believe if you try to load those old files v3.1 will try to convert them to the new format, but no promises.

**Comment by billylau12** [comment]
Thank you for your response, @DrCoffey!  The main reason I need those columns is because we have another script that will collate all the information from multiple detection files into one file. I have attached that script here (which works for DeepSqueak v2.6 detection files), and it's lines #20-23 that shows all the data that we need.  It seems like in your script 'recordAudio_Callback.m' is storing the latter half of these data (yellow highlight in the attached word doc)? Could you advice on how to retrieve those data? Apology for my lack of understanding of Matlab.
Thanks again!
Billy
[Collate.docx](https://github.com/DrCoffey/DeepSqueak/files/11442233/Collate.docx)
