### ISSUE TITLE
Call Feature (Slope) Explanation 

### ISSUE THREAD

**Issue by babywing** [DrCoffey/DeepSqueak#204]
Hi! I am interested in analyzing call features, and I noticed the "Slope (kHz/s)" feature in the call stats file. I understand this feature is about the contour, but what information does Slope provide compared to Delta Freq? I checked the values, and the slope for some calls is -600 kHz/s -- thus, to my understanding, this is not the change in frequency of the call (and I'm assuming that's what delta freq is). Can you please define what "Slope" is as a USV property? 

It also might be helpful to provide a glossary to interpret some of these features in the context of USVs. 
Thank you so much!

**Comment by VoiceScientist** [comment]
Delta frequency is simply the difference between the highest and lowest frequencies detected in the contour. The slope gives you the linear change in frequency over time of the contour. I don’t know exactly how it is calculated, but I think it’s a line of best fit (someone correct me on that). There is a minimal description of the output parameters on the wiki here:
https://github.com/DrCoffey/DeepSqueak/wiki/export-to-excel
Hope that helps!

**Comment by DrCoffey** [comment]
@VoiceScientist is correct. Slope is calculated via a linear best fit on the entire extracted contour.

**Comment by babywing** [comment]
Thank you! I definitely need a more detailed explanation for the slope. I have interesting data regarding that feature, and I want to interpret the results as best as possible. Is slope only used for detection/classification? Or is it a meaningful USV property?

**Comment by DrCoffey** [comment]
That is a great question, and one I don't really know the answer to. I'll say that slope is a relevant descriptor for simple calls (flat, up sweeps, etc.) but it doesn't do a good job capturing complex calls with multiple components. The attached example call has 2 sweeps, one up and one down, but the linear best fit line just goes up...
![image](https://github.com/DrCoffey/DeepSqueak/assets/39605011/44c94999-fa71-4729-bdb4-44df5cfefa54)
![image](https://github.com/DrCoffey/DeepSqueak/assets/39605011/b18ec86d-08e3-4404-8372-840d256a0ab0)

**Comment by babywing** [comment]
Thank you so much! This is actually very helpful. I appreciate your explanation and examples!
