### ISSUE TITLE
VAE Issue

### ISSUE THREAD

**Issue by VFonsi** [DrCoffey/DeepSqueak#205]
I'm trying to use the unsupervised clustering feature using an extracted contours file, but before it finishes, the function stops and produces the error attached. 
![image](https://github.com/DrCoffey/DeepSqueak/assets/141602718/f71d7f48-622e-48df-aa00-17d5b49d873f)

It mentions "out of memory" but I have used larger extracted contours files before with no problem. 

Any advice or ideas for this issue are greatly appreciated, 
Thank you!

**Comment by DrCoffey** [comment]
Hey @VFonsi, I haven't seen this before. Do you get into the training window first or does it crash before the graph pops up?

**Comment by VFonsi** [comment]
I do get the training window to pop up but once it appears, the error messages pop up. The graph is displayed but at seemingly the same time, it crashes.
