### ISSUE TITLE
Export to excel error

### ISSUE THREAD

**Issue by jordanes** [DrCoffey/DeepSqueak#208]
Hello! I'm running DeepSqueak 3.1.0 on Windows 11, Matlab R2022a. I'm encountering the following error when I attempt to export call statistics to excel:

![image](https://github.com/DrCoffey/DeepSqueak/assets/23603287/2d74a262-b4ec-444a-ad55-f50ee0e836e8)

The export seems to freeze about 3/4 of the way through (as indicated by the progress bar). 

Here are the WAV and detection files.
https://drive.google.com/drive/folders/1iWa7yYNbOaXaQKrbl4mrAgDSg9zl3FHy?usp=sharing

Thank you!

**Comment by DrCoffey** [comment]
Call 1186 was giving it issues, not sure why. I just deleted it and it worked. 

I also noticed you very boxing the harmonics on your 22s separately. These are really not separate calls, so you shouldn't count (box) them twice.

[2023-07-31 ch1ch1 2023-08-01 11_03 AM - KC.zip](https://github.com/DrCoffey/DeepSqueak/files/12365511/2023-07-31.ch1ch1.2023-08-01.11_03.AM.-.KC.zip)

**Comment by jordanes** [comment]
> 

Thank you!

**Comment by vanesass** [comment]
> Call 1186 was giving it issues, not sure why. I just deleted it and it worked.
> 
> I also noticed you vare boxing the harmonics on your 22s separately. These are really not separate calls, so you shouldn't count (box) them twice.
> 
> [2023-07-31 ch1ch1 2023-08-01 11_03 AM - KC.zip](https://github.com/DrCoffey/DeepSqueak/files/12365511/2023-07-31.ch1ch1.2023-08-01.11_03.AM.-.KC.zip)
I am having a similiar issue. How did you know which call was causing the issue?

**Comment by DrCoffey** [comment]
Use debugging mode. Turn on "Pause on Error" under the "Play Button" and then look which call was trying to be saved when it fails

**Comment by vanesass** [comment]
[USVsERRORexport.zip](https://github.com/DrCoffey/DeepSqueak/files/15062025/USVsERRORexport.zip)
Hello, Thank you for your reply. I tried to do that but I don't see which number of call there is. I tried to count the messages to figure out the call but there are just too many. I have attached the files in case you could take them a look.  Also, once you know which call it is, in DeepSqueak is there a way to go directly to one call position or if let's say it was call number 256 I have to pass one by one 256 calls until I find it. Many thanks.

**Comment by mgraziano1230** [comment]
Hello, I am having a similar issue. I turned on "pause on error" to check where it is failing, but I only see which line of code is involved, not which number of call is trying to be saved when it fails. Could you please tell me where to see which number of call is trying to be saved when it fails?
