### ISSUE TITLE
Error message when loading calls

### ISSUE THREAD

**Issue by elizamackenzie** [DrCoffey/DeepSqueak#227]
I keep getting these errors when I go to load calls:

Error using rectangle
Unrecognized property FaceAlpha for class Rectangle.

Error in initialize_display (line 92)
handles.currentWindowRectangle = rectangle(handles.spectogramWindow,...

Error in loadcalls_Callback (line 60)
initialize_display(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

The DeepSqueak rat graphic inverts itself under the original one and the calls don't load. I have matlab 2021a.

**Comment by kylieziemke** [comment]
I am having the same issue, where the DeepSqueak graphic is inverted, I get the same errors in matlab, and no calls show up in DeepSqueak when I try to load calls. I have matlab 2023b.

**Comment by kylieziemke** [comment]
For more context, I am working on a Mac Studio 2023 with Apple M2 Max Chip. I have tried closing and restarting DeepSqueak, and I have reset the network, detection, and audio files. I can detect calls but cannot load any of the detected calls without getting an inverted DeepSqueak graphic. I also have the same issue when trying to load any of the calls from the example mouse or rat recordings.

**Comment by shiave** [comment]
I'm dealing with the same issue here. I am also working with matlab 2021a. I'm also getting an inverted graphic. Below is my exact error:

Error using rectangle
Unrecognized property FaceAlpha for class Rectangle.

Error in initialize_display (line 92)
handles.currentWindowRectangle = rectangle(handles.spectogramWindow,...

Error in loadcalls_Callback (line 60)
initialize_display(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

@DrCoffey Any tips?

**Comment by DrCoffey** [comment]
Sorry for the slow reply here, I don't have a lot of time for DeepSqueak tech support these days. It looks like FaceAlpha was added to the Rectangle Class in Matlab 2024a. I must have added it to the code without realizing it would break on older versions. I will find a fix for backwards compatibility, but if you update to 2024a it should work fine.

**Comment by DrCoffey** [comment]
@shiave @elizamackenzie @kylieziemke - Update DeepSqueak and it should now work on older versions.

**Comment by shiave** [comment]
@DrCoffey Thank you so much! It is working now on 2021a. Haven't tried 2024a yet.
