### ISSUE TITLE
Call detection of multichannel wav files

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#26]
Hey there,

sorry for another question.

How would you detect calls that were recorded with several microphones? 

Would you split the channels into separate files and do the detection separately in these channels? Or is there a functionality allowing simultaneous detection of the same recording in several channels?

Cheers,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

Aaron answered pretty completely. You can merge the files after detection with the "Merge Detection Files" tool, or you can merge audio files before detection. It would likely be faster to merge beforehand. 

-Kevin

**Comment by MxMarx** [comment]
Currently, DeepSqueak will only process the first channel of audio files with more than a single channel. It probably wouldn't but too hard to modify it to process each channel separately, but if the microphones are relatively close to each other, you might have better signal to noise by merging the audio channels together before detection.

**Comment by imgross** [comment]
Hey everyone,

thanks very much for your help! This is exactly what I was looking for :)

Cheers,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

I think you will have to pick 1 of the channels to create the merged file. We will look into dealing with multi-channel files and perhaps merge the audio automatically. Would it be more valuable to you to do a mean merge or a max merge? I assume max may be better if some calls are only picked up by 1 mic?

-Kevin

**Comment by DrCoffey** [comment]
Actually, would you be opposed to sending us a minute or so of your 4 channel recording with a call in it? That would make it really easy to test.

**Comment by imgross** [comment]
Yes, I think a max would be the best idea.

I can totally send you a wave file. To which mail address should it go?
And the recordings are like 5 min, should I shorten them?

Thanks,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

Sorry I haven't responded, been a little sick.  You can send it to mrcoffey[at]uw.edu

**Comment by DrCoffey** [comment]
Hey Isa,

Do you still want to send us some multi channel audio? We have some time to work on it now.

-Kevin

**Comment by MxMarx** [comment]
I changed to code so that if audio files have multiple channels, the mean of the channels is used.
We also played around with making max intensity projections of audio and the left the code unused. If you want to try it, it's in a switch statement at line 84 of SqueakDetect.m

**Comment by VoiceScientist** [comment]
That's fantastic - thank you!

**Comment by imgross** [comment]
Cool, thank you very much! I will test it :)
