### ISSUE TITLE
Merge Detection files

### ISSUE THREAD

**Issue by BavoKempen** [DrCoffey/DeepSqueak#28]
Hey Kevin and Russell,

I tried to merge multiple detection files of the same recording (k>2 ) through the merge detection files function in the GUI, however I keep bouncing upon the same error. 

```
Error using audioread (line 135)
Range requested is greater than the total number of samples in the file. TotalSamples is 7405568.

Error in merge_Callback (line 74)
a = audioread([audiopath audiodata],[WindL WindR],'native');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('merge_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.
```
Also, I tried rejecting the last call of each detection file since this solved a similar issue in the past, nonetheless, the error keeps occurring.  Furthermore, I looked into the code concerning the multinetdect_Callback.m and I am wondering why do you not allow for k>2 networks to run on the same audio file concurrently and merge them afterwards as it is allowed with 2 networks.

Kind regards,

Bavo Kempen

**Comment by DrCoffey** [comment]
Hey Bavo,

Sorry about the delay, things have been crazy in Seattle with some record snowfall. We'll take a look at letting you use an arbitrary number of detection networks. The error still suggests that a call is at the very end of the file, but we will also look into a smarter way of dealing with that than just deleting the last call.

Kevin

**Comment by DrCoffey** [comment]
Hey Bavo,

You can now use as many networks as you want, and it shouldn't matter if there are calls at the end of the file.  If you run into any more issues let us know!

-Kevin

**Comment by BavoKempen** [comment]
Hey Kevin,

Great, thanks for implementing this!
Kind regards,

Bavo
