### ISSUE TITLE
GNU Octave

### ISSUE THREAD

**Issue by dpastern** [DrCoffey/DeepSqueak#30]
Hey guys,

Will these modules run with GNU Octave?  Matlab is not an option (money!).  

Cheers,

Dave

**Comment by DrCoffey** [comment]
Hey Dave,

We haven't tested DeepSqueak in Octave. It is pretty complicated code, so I imagine you would run into issues. I would have liked to be completely open source with DeepSqueak, but I have been coding in Matlab so long that it was really the only option for us. 

-Kevin

**Comment by dpastern** [comment]
Dang!  A lad can always hope!  I was more curious about my pet rats, than anything serious science wise.  

Did you notice vocalisation changes in rats with ill health (mycoplasma etc)?

**Comment by clemens-tolboom** [comment]
@dpastern have to tried Octave? I did using https://flathub.org/apps/details/org.octave.Octave to get 5.x (Ubuntu gave me 4.x)

DeepSqueek.m is not runable.

```matlab
>> DeepSqueak

error: 'gui_mainfcn' undefined near line 30 column 5
error: called from
    DeepSqueak at line 30 column 5
```

Unfortunately (to me) the *.mat files (guess those are HDF5?) could not be opened due to bug/feature in Octave https://savannah.gnu.org/bugs/?45706

**Comment by clemens-tolboom** [comment]
Trying to read the `*.mat` file(s) with python https://stackoverflow.com/questions/874461/read-mat-files-in-python#874488 has some good references.

**Comment by MxMarx** [comment]
I'm guessing that this is because the *.mat files were all saved as v7.3, be we could probably compile it into a standalone application. I tested it on windows, and detecting and viewing files seemed to work.
