### ISSUE TITLE
Error in Network, Skiping Audio Chunk

### ISSUE THREAD

**Issue by BavoKempen** [DrCoffey/DeepSqueak#31]
Dear Kevin and Russell, 

I updated DeepSqueak yesterday to the latest version, however, it seems that a bug slipped in. Thus, with both the functions "detect calls" and "multi detect" the script crashes and gives the following error. I think it has to do with the recent update on multichannel audiofiles. Furthermore, I also got this error when I just ran a Network inherent with DeepSqueak (e.g. All Short Calls_Network.mat).

```
Error in Network, Skiping Audio Chunk
Warning: Error using buffer
invalid input argument #1

Error in datawrap (line 21)
x = sum(buffer(x,nfft),2);

Error in computeDFT>computeDFTviaFFT (line 83)
        xw(:,j) = datawrap(xin(:,j),nfft);

Error in computeDFT (line 47)
    [Xx,f] = computeDFTviaFFT(xin,nx,nfft,Fs);

Error in pspectrogram (line 63)
  [y,f] = computeDFT(bsxfun(@times,win,xin),nfft,Fs);

Error in spectrogram (line 166)
  [varargout{1:nargout}] = pspectrogram({x},'spect',varargin{:});

Error in SqueakDetect (line 95)
        [s,fr,ti] =
        spectrogram(audio(:,1),wind,noverlap,nfft,audio_info.SampleRate,'yaxis');
        % Just use the first audio channel

Error in multinetdect_Callback (line 77)
        Calls = [Calls,
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];
        
Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
> In SqueakDetect (line 168)
  In multinetdect_Callback (line 77)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
```

Kind regards,

Bavo Kempen

**Comment by DrCoffey** [comment]
Hey Bavo,

The update seems to be working on all of our audio files, can you send me an offending file?

Thanks,
Kevin

**Comment by BavoKempen** [comment]
Hey Kevin,

The file that I shared with you some time ago on dropbox should recreate this error :)

Kind regards,

Bavo Kempen

**Comment by DrCoffey** [comment]
I just cloned the Master Branch and detected AN1.wav and AN12.wav and they both worked on a couple computers with all of the networks. Can you open SqueakDetect.m and under the "Run" drop down menu hit "Pause On Errors". Then can you re-create the error, save and send us the workspace?

**Comment by DrCoffey** [comment]
Also. when you pause on error, you can change the workspace in a drop down menu. Make sure it is on the SqueakDetect workspace.

**Comment by BavoKempen** [comment]
Dear Kevin and Russell,

I sent the workspace .mat file through email, thanks for taking a look at it!

Kind regards,

Bavo Kempen

**Comment by DrCoffey** [comment]
Hey Bavo,

I should have been a little more clear with my instructions. The workspace you sent is from the wrong function. You need the workspace from SqueakDetect. There are 2 ways you can do this.

1. Pause on errors, and then change the "Function Call Stack" drop down to SqueakDetect

2. Put a debug dot before the offending line. I have attached a picture for reference.

I also detected the file in the drive link fine over here, and uploaded the .mat. We have an experimental branch we are working on called "detect as tables" that might just fix your problem.

-Kevin

![capture](https://user-images.githubusercontent.com/39605011/53993683-f47c0380-40e4-11e9-98ed-9ad2da3cca9d.JPG)

**Comment by BavoKempen** [comment]
Hey Kevin,

While implementing the above mentioned workspace extractions, peculiar enough everything ran smoothly again, thus no error anymore to report. Sorry for the inconvenience, very weird though since I did not change a thing. Anyways, thanks as always for the rapid and good help!

Kind regards,

Bavo Kempen

**Comment by BavoKempen** [comment]
Hey again,

Another related problem I think is that now it takes really really long to merge boxes during detection (up to 10 minutes) for audiofiles that are approximately 5 minutes long, whereas this was not the case prior to the update. 
I believe and correct me if I am wrong but my specs should be able to handle that or atleast they could before: 
1) Processor: Intel(R) Core(TM) i7-6500U CPU
2) 8,0 GB RAM DDR3
3) GPU: NVIDIA GeForce 940M
4) SSD harddrive

Any idea why this might be the case? Is it a combination of the length of the respective files concurrent with the change in merge_boxes.m function that substracts from mean?

Kind regards,

Bavo Kempen

**Comment by DrCoffey** [comment]
Hey Bavo, We have solved that problem and will upload a major update today. We are just trying to test everything before the push.

**Comment by BavoKempen** [comment]
Hey Kevin,

That is great news, thanks for the fast updates!

Kind regards,

Bavo Kempen

**Comment by BavoKempen** [comment]
Dear Kevin and Russell,

Thanks a lot for the great update, detection runs a lot smoother again!

Kind regards,

Bavo
