### ISSUE TITLE
Mapping EEG to audio

### ISSUE THREAD

**Issue by thothP** [DrCoffey/DeepSqueak#34]
(should preface that I'm probably spewing nonsense ie layman)

**Is your feature request related to a problem? Please describe.**
The recent verge video  noted more research was required in order to interpret the meaning of particular squeaks frequencies from the mice.  Would like to know if this suggestion makes sense.

**Describe the solution you'd like**
This solution depends on whether human EEG signals  emitted from a particular region in the brain (that we know indicate a particular emotion)  would approximately correlate with a rats ie whether comparing the EEG reading from the rats brain during squeaking a particular  frequency may assist in understanding the emotion (when comparing source of the EEG signal from the rat brain to the human brain).   This article describes a recently released EEG monitor that would be perfect for rats https://www.janelia.org/news/neuropixels-technology-ready-for-release  

**Describe alternatives you've considered**
Crowdsourcing the research with those who have rats as pets, especially the real rat lovers (and even petshop owners). There expereince and time spent with the rats could provide invaluable information (eg they record the frequencies and at the same time they would intuitively know the particular mood of the rat (hungry , sad, tired, confused  etc). 

**Additional context**
none

**Comment by DrCoffey** [comment]
Hey thothP,

Thanks for your interest in DeepSqueak and your advice. We are hoping someone else will look into using EEG and vocalizations together, but it is outside our scope. 

Also, looking at pet rats would be really cool, but unfortunately it isn't a controlled environment, making it not ideal for scientific analysis.

-Kevin
