### ISSUE TITLE
Batch Reject and other issues

### ISSUE THREAD

**Issue by Marrekko** [DrCoffey/DeepSqueak#35]
Dear Kevin and Russel,

first of all thank you for your great work with DeepSqueak. A automated and powerful tool for USV detection was urgently needed in terms of time consumption for analysis!

Im testing DS for our lab since a while and most of us have been positively surprised by the first results. However, those were made analysing recordings from operant chambers meaning well defined and easy to filter noise and no problems with call intensity. For the next tests i analysed open field data wherein noise is more diverse and calls are less intense, given the big recording space. I found that detection rate is only sufficient using the short_rat_call network V2 under high recall settings. Of course this comes with a lot detected noise, which i can get rid of with a trained denoising network. Anyway, i also tried batch reject by several parameters which did not work out at all. In addition, the prompt looks like this on my machine:
<img width="688" alt="threshrejectpic2" src="https://user-images.githubusercontent.com/48712095/54603758-705f3f80-4a45-11e9-905a-09a4c244c271.png">

Like that i cant see the full prompt or move it. Can you replicate that or is it limited to my machine (Windows 10, Matlab2018b V3, DS 2.5)? 

My second point regards the tonality function as this is critical for extracted parameters. While processing calls, it would be very helpful to have fix shortkeys for adjusting the tonality of a call or at least the option to set some. Is that possible?

As we are several researchers working on different questions, it can be possible that we would need additional parameters extracted from calls. So in general: How complicated is it to add parameters to exported excel sheets and can we contact you on that matter?

Last but not least, i recently read [in a comment by Russel](https://github.com/DrCoffey/DeepSqueak/issues/30#issuecomment-469084637) that you might work on a standalone to make DS totally open source. This would make DS even more interesting for us, so do you actually work on this issue?

Thanks again and cheers

Marek

**Comment by DrCoffey** [comment]
Hey Marek,

Tonality thresholds can be adjusted using the slider next to the tonality graph. It will effect the tonality threshold for all calls in the files.  

I think the batch reject is off the screen because you have a low resolution monitor. Russell is working on a little fix to  make sure the window will show up on any screen.

You can modify the CalculateStats.m code if you want to calculate different statistics, but you would need to know how to code in matlab. You would also likely need to modify the excel_Callback.m.

We are definitely going to release a standalone version of DeepSqueak very soon, but it won't receive the support or updates that the main branch does.

-Kevin

**Comment by MxMarx** [comment]
Hi Marek,

The batch reject by threshold window should now appear on the screen.
Were you getting a specific error from batch reject? The error would appear in the Matlab command window.

[I've compiled DeepSqueak into an executable.](https://github.com/DrCoffey/DeepSqueak/releases)
I've tested it on my computer running Windows 10 and detection and clustering all seemed to work.

What particular parameters would you like to extract? The way to do it would be to calculate them in CalculateStats.m, which excel_Callback uses to create the output.

-Russell

**Comment by Marrekko** [comment]
Hey Kevin, hey Russel,

thank you for your fast answer! Before updating the new files i checked for error messages (was not the case) and tried different resolutions than my 1920x1080 (didnt work). However, with the update the prompt shows up correct and batch reject works fine now, so thanks a lot for this very quick problem solving!

Also, thank you for the executable standalone! I will for sure test it next week, really good job again! But as you said it wont get as much support as your main branch, is it general possible to build a standalone with new updates by ourself using some python tools? 

We are not sure which parameters we will need in future but knowing which files have to be edited is definitely big step forward, thank you!

> Tonality thresholds can be adjusted using the slider next to the tonality graph. It will effect the tonality threshold for all calls in the files.

Actually, i was totally unaware of that. Of course i know the slider but i didnt knew it changes tonality for all calls. What is the reason for that and is there a way to bring this feature up for individual calls? In general the automatic tonality setting works pretty good, but i found it necessary to adjust it for some cases to get a proper fitting contour and therefor extracted statistics of the call. 

Thank you so much again for your superb support!

Marek

**Comment by VoiceScientist** [comment]
I second the request for adjusting tonality for individual calls. We have the same issue with needing to adjust the setting for some calls to improve the contour, but not all - mostly it depends on the SNR of individual calls. I also echo Marek's appreciation of your superb support!
Aaron

**Comment by DrCoffey** [comment]
Hey Aaron & Marek,

I see the value of adjusting tonality of individual calls, but it seems difficult to implement. We tend to us DeepSqueak on huge data sets (10's of thousands of calls). Adjusting tonality for all calls is basically impossible, so we have to rely on a

**Comment by Marrekko** [comment]
Dear Kevin and Russel,
I hope you are good and you still have a little bit of time for DS. Sorry for coming back to this issue, but whilst analyzing a new data set I found a bug in the Windows standalone version. This regards training of the denoising Network, such to say a core function of DS, and was replicated on several machines. 
`Error using trainNetwork (line 150)
Deployment of training progress plot not supported.

Error in TrainPostHocDenoiser_Callback (line 143)

Error in gui_mainfcn (line 95)

Error in DeepSqueak (line 30)

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('TrainPostHocDenoiser_Callback',hObject,eventdata,guidata(hObject))

Error using waitforallfiguresclosed (line 9)
Error while evaluating Menu Callback.
`
Obviously, the Matlab Compiler Runtime has problems to generate figures (a common problem with compiled scripts). As I dont find those figures to be necessary I would change code to not generate those. However, the Matlab compiler is a product we don't have access to. Do you have any solution for this, or find a way to change the compiled Windows version with less effort?

Best
Marek

**Comment by MxMarx** [comment]
Hi Marek,

I've recompiled everything with the newest version of Matlab, hopefully that fixed the issue.
If it doesn't let me know and I'll make it not show the plot in the compiled version.

**Comment by Marrekko** [comment]
Hi Russel,

thank you so much for the work and the effort! I'm very sorry but I just tried it and it seems to have the same problem. Everything else seems to work fine as in the previous version. 

Best 
Marek
