### ISSUE TITLE
Network training does not initiate 

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#37]
Hi there,

I am having trouble with training a network with my detected calls and I am receiving this error message when trying to train a network:

Error using trainNetwork (line 154)
An error occurred while trying to determine whether "readData" is a function name.

Error in TrainSupervisedClassifier_Callback (line 152)
ClassifyNet = trainNetwork(auimds,layers,options);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('TrainSupervisedClassifier_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    An error occurred while trying to determine whether "readData" is a function name.
        Can't reload 'D:\MATLAB\R2018a\bin\win64\sl_graphical_classes.dll'
 
Error while evaluating Menu Callback.

Would you have an idea what I am doing wrong here?

Thanks for your support!!

Cheers,
Isa

**Comment by MxMarx** [comment]
Network training seems to work fine for me.

I googled the error and it might have something to do with the matlab path.
See https://www.mathworks.com/matlabcentral/answers/441088-an-error-occurred-while-trying-to-determine-whether-readdata-is-a-function-name and https://www.mathworks.com/matlabcentral/answers/441310-matlab-2018b-readtable-error-after-update

Could you have another file in your path named readData?

**Comment by DrCoffey** [comment]
Hey Isa,

Were you able to resolve this issue?

**Comment by imgross** [comment]
Yes, thank you!
