### ISSUE TITLE
Error with t-SNE

### ISSUE THREAD

**Issue by stowerslab** [DrCoffey/DeepSqueak#38]
I get the following error when trying to plot the t-SNE:

Error using CreateClusteringData
Too many input arguments.

Error in create_tsne_Callback (line 26)
[a] = CreateClusteringData(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('create_tsne_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.

The call files were loaded and clustered before trying to plot the t-SNE.

**Comment by MxMarx** [comment]
Should be fixed now
