### ISSUE TITLE
Error Initializing

### ISSUE THREAD

**Issue by zach-gutz** [DrCoffey/DeepSqueak#40]
I get this error when trying to start DeepSqueak on macOS 10.14.4, MATLAB R2018b.

<img width="688" alt="Screen Shot 2019-04-08 at 12 17 13 PM" src="https://user-images.githubusercontent.com/35212327/55750638-9189cf00-59f8-11e9-856b-ab13d1bd5430.png">

**Comment by DrCoffey** [comment]
Hey Zach,

We have DeepSqueak working on some Macs here so I'm not sure what the issue is. I will take a look and get back to you. If I can't figure it out, I may ask you to pause on error and send me the workspace.

-Kevin

**Comment by MxMarx** [comment]
I think the issue might have something to do with a built-in MATLAB function with the same name but different case. I couldn't replicate the issue, but I've renamed the function, so hopefully that solves it.

-Russell
