### ISSUE TITLE
Error with Denoising

### ISSUE THREAD

**Issue by LWilkinKrug** [DrCoffey/DeepSqueak#44]
**Describe the bug**
When running Post Hoc Denoiser I get the following error:

Index in position 2 exceeds array bounds (must not exceed 2020).

Error in PostHocDenoising_Callback (line 52)
        I=abs(s(round(y1:min(y2,size(s,1))),round(x1:x2))); % Get the pixels in the box

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('PostHocDenoising_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

**To Reproduce**
1. Go to Tools>Post Hoc Denoiser
2. Click on files you want to denoise
3. Click OK

**Expected behavior**
Denoise files

**Additional context**
MacOS 10.14.5
MatLab 2018a (fresh install)

**Comment by MxMarx** [comment]
It looks like one of the boxes somehow extends past right boundary of the spectrogram. Do you know how that might have happened?
I've updated the code so that the box is clipped within the spectrogram.

Let me know if this fixes it,
-Russell

**Comment by LWilkinKrug** [comment]
Thanks Russell, 
I've replaced the file and now cannot run the Denoiser at all. 

**Bug**

Error: File: PostHocDenoising_Callback.m Line: 7 Column: 1
Invalid use of operator.

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('PostHocDenoising_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

**To Reproduce**

Steps to reproduce the behavior:

Go to Tools>Post Hoc Denoiser
Observe that nothing happens and find the error in Matlab command window

**Comment by DrCoffey** [comment]
We highly recommend using GitHub Desktop to update DeepSqueak. It gets around a lot of issues with duplicate versions and path issues. Good luck!

-Kevin

**Comment by ralphpeterson** [comment]
Hi all,

I have used older versions of DS and the most recent version of DS and am also getting the above issue. Any advice on how to solve it?

Here is the error traceback:

```
Index in position 2 exceeds array bounds (must not exceed 59).

Error in TrainPostHocDenoiser_Callback (line 54)
            I=abs(s(round(y1:min(y2,size(s,1))),round(x1:x2))); % Get the
            pixels in the box

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 34)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('TrainPostHocDenoiser_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.
```
