### ISSUE TITLE
Error/Warning when running multidetect

### ISSUE THREAD

**Issue by LWilkinKrug** [DrCoffey/DeepSqueak#45]
Hi again, 

**Describe the bug**
When running a multi detect, I get the following errors on various files

 MException with properties:

    identifier: 'MATLAB:struct2table:UnequalFieldLengths'
       message: 'Input structure is a scalar, but its fields have different numbers of rows. If you intended to create a table with one row, set 'AsArray' to true.'
         cause: {}
         stack: [8×1 struct]

MException with properties:

    identifier: 'MATLAB:badsubscript'
       message: 'Index in position 1 exceeds array bounds (must not exceed 961).'
         cause: {}
         stack: [6×1 struct]

**Operating system / MATLAB version**
MacOS 10.14.5
Matlab 2018a

**Comment by DrCoffey** [comment]
Hey, sorry this took so long to respond. This looks like a Mac specific error, but I'm not sure whats causing it. Are you using the latest version of DeepSqueak, and are you still running into this error?

**Comment by LWilkinKrug** [comment]
Hey there and the apologies go right back at you! I've just picked up the analysis of my pup USVs again. I've pulled the latest files and have run a couple of analyses, but it seems the issue is resolved. Let's close it for now.
