### ISSUE TITLE
Unsupervised call classification

### ISSUE THREAD

**Issue by lhobson13** [DrCoffey/DeepSqueak#46]
Hello, 
         Just to repeat what everyone else has been saying- thank you very much for the software! 

I am moving to try to use the unsupervised call classification. I have seen the below error and I am wondering if this occurred because there are few calls in the detection files I used? I see that some of my animals call very infrequently, so if this is the issue is there any way that this can be resolved?

Also, I have a question about the weightings for shape, duration and frequency. Specifically, is there any way to calculate the appropriate weight for each variable?

Thank you very much for your help.   

Error using waitbar (line 100)
The second argument must be a message character vector or a handle to an existing waitbar.

Error in CreateClusteringData (line 43)
            waitbar(i/height(file.Calls),h,['Loading File ' num2str(j) ' of '  num2str(length(fileName))]);

Error in UnsupervisedClustering_Callback (line 5)
[ClusteringData] = CreateClusteringData(handles.data, 1);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('UnsupervisedClustering_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating Menu Callback.

lowering threshold
lowering threshold
lowering threshold
Error using kmeans (line 277)
X must have more rows than the number of clusters.

Error in kmeans_opt (line 53)
    [~,~,dist]=kmeans(X,c,'emptyaction','drop'); %compute the sum of intra-cluster distances

Error in UnsupervisedClustering_Callback (line 64)
                            [clustAssign,C]=kmeans_opt(data,str2num(opt_options{1}),0,str2num(opt_options{2}));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('UnsupervisedClustering_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating Menu Callback.

**Comment by DrCoffey** [comment]
It sounds like the number of clusters you chose is greater than the total number of calls. Are you selecting multiple detection files for clustering? We recommend clustering an entire data set at once. All you have to do is select multiple detection.mat files when prompted. If that is not the issue then let me know and we'll take a closer look.

**Comment by lhobson13** [comment]
Hello, thank you for your fast response. I had selected over 40 detection files and allowed deepsqueak to determine the appropriate number of clusters. I could try again with files that have a larger number of calls (many of the files may have contained no calls at all, I would guess there were fewer than 50 calls in total). Maybe if I use files with a greater number of calls I can use the models to classify calls when the number is low like this?

**Comment by DrCoffey** [comment]
Ok, what happened is you attemted the elbow optimized clustering with a max of 100. When the cluster number went over 50, the algorithm couldn't assign any calls to some clusters and crashed. Just make sure you pick a smaller number of clusters than you have calls. Are you looking at mouse or rat USVs?

You could use the built in K-means model or neural network to classify any number of rat USVs

**Comment by lhobson13** [comment]
That makes sense. Thank you so much for all your help. I am classifying mouse calls, so unfortunately I cant use those networks.
