### ISSUE TITLE
Error creating t-sne plot

### ISSUE THREAD

**Issue by madalenaesteves** [DrCoffey/DeepSqueak#47]
Hi,

thanks a lot for this great software, we are getting very interesting data.

When trying to create the t-sne plot from either detection files or extracted contours, I am getting the error:

Error using CreateClusteringData
Too many input arguments.

Error in create_tsne_Callback (line 26)
[a] = CreateClusteringData(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('create_tsne_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

When first exploring DeepSqueak, a few months ago, we were able to do this, so we can't seem to understand what the mistake is. I am using Matlab R2018b and DeepSqueak 2.5.0

**Comment by DrCoffey** [comment]
Hey Madalena,

Can you try updating to 2.6.0 (the newest version) and see if that fixes the problem?

Also, are you trying to color the calls by frequency or cluster label?

Thanks,
Kevin

**Comment by madalenaesteves** [comment]
Hi,

I was trying to do it by frequency as it was the only one available in the previous version. Updating to 2.6.0 worked and I am now able to do both.

Thanks a lot.
Madalena

Enviado do Correio para Windows 10

De: DrCoffey
Enviado: 18 de junho de 2019 19:40
Para: DrCoffey/DeepSqueak
Cc: madalenaesteves; Author
Assunto: Re: [DrCoffey/DeepSqueak] Error creating t-sne plot (#47)

Hey Madalena,
Can you try updating to 2.6.0 (the newest version) and see if that fixes the problem?
Also, are you trying to color the calls by frequency or cluster label?
Thanks,
Kevin
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Este e-mail foi verificado em termos de vírus pelo software antivírus Avast.
https://www.avast.com/antivirus
