### ISSUE TITLE
Ability to select call that has not been detected by DS

### ISSUE THREAD

**Issue by LW-Krugie** [DrCoffey/DeepSqueak#49]
**Problem**
I work mainly with rat pup USVs. These are quite unique and while using Multi-detect (short and long rat calls) work well, often I'd like to be able to manually add a call selection. At present, I can only work with the number of calls detected by the system. 

This is particularly tricky when working with multiple animals. While the labels allow me to assign calls to different animals, I cannot add a call when calls overlap.

**Solution**
The ability to add a brand new call/select call

**Comment by DrCoffey** [comment]
If the calls are overlapping in time that could be tricky for the rest of the algorithm (contour and stats calculation). If you send us an example audio clip we can take a look, but no promises.

**Comment by LWilkinKrug** [comment]
I've sent you a Dropbox link with examples

**Comment by ARTUR551** [comment]
> **Problem**
> I work mainly with rat pup USVs. These are quite unique and while using Multi-detect (short and long rat calls) work well, often I'd like to be able to manually add a call selection. At present, I can only work with the number of calls detected by the system.
> 
> This is particularly tricky when working with multiple animals. While the labels allow me to assign calls to different animals, I cannot add a call when calls overlap.
> 
> **Solution**
> The ability to add a brand new call/select call

I have a similar problem, my model induces changes in call properties. I want to verify that DeepSqueak is performing good enough compared with manual classification. 
I found a version that allows you to Review the entire Spectrogram to find undetected calls or modify the detected ones.

It works fine, but it is a little slow for my taste. I don't know if it is a Matlab problem.

![image](https://user-images.githubusercontent.com/58208550/69611702-0e74c200-1037-11ea-9383-5744897a1b45.png)

https://github.com/UEFepilepsyAIVI/DeepSqueak

Regards!

Arthur

**Comment by LWilkinKrug** [comment]
> I have a similar problem, my model induces changes in call properties. I want to verify that DeepSqueak is performing good enough compared with manual classification.
> I found a version that allows you to Review the entire Spectrogram to find undetected calls or modify the detected ones.
> 
> It works fine, but it is a little slow for my taste. I don't know if it is a Matlab problem.
> 
> ![image](https://user-images.githubusercontent.com/58208550/69611702-0e74c200-1037-11ea-9383-5744897a1b45.png)
> 
> https://github.com/UEFepilepsyAIVI/DeepSqueak
> 
> Regards!
> 
> Arthur

Hey Arthur, 

What do you mean by "I found a version that allows you to Review the entire Spectrogram to find undetected calls or modify the detected ones"? What version is that?

**Comment by ARTUR551** [comment]
In the link I've put previously:
https://github.com/UEFepilepsyAIVI/DeepSqueak
You can download it and add it in a new folder to Matlab.
It is an improved version or Fork? I'm new in Github...
They added a way to inspect the entire file and manually add calls that are not detected by DeepSqueak. As you can see in the image. There are some instructions in the main page.

Arthur

**Comment by LWilkinKrug** [comment]
Hey Arthur, 

While I can analyse fils with it, I can't load them. I get the following error:

_DeepSqueak Screener, base DeepSqueak version 2.6.1_
```
Undefined function or variable 'loadAudioData'.

Error in loadcalls_Callback (line 29)
[samples, duration,sample_rate] = loadAudioData(audio_file_path);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 34)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```

**Comment by rciszek** [comment]
Hi @LWilkinKrug, 

Can you try again using the most recent version?

**Comment by LWilkinKrug** [comment]
@rciszek, it seems it only loads Detection files generated by Screener. Any detection file generated with the base version of DS results in an error

```
Dot indexing is not supported for variables of this type.

Error in loadcalls_Callback (line 28)
audio_file_path =  strcat(handles.data.settings.audiofolder,filesep, handles.data.audiodata.AudioFile);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 35)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
```

**Comment by ARTUR551** [comment]
@rciszek, detection files are not recognized by the original DS. I post this since some functionalities (as playing the calls, separating long calls, and some others that I've tested) are not working in the Screener version. How can both version files can be compatible? Just as @LWilkinKrug says, it would save time instead of analyzing again all files with Screener.

Screener is very useful BTW, nice job! It adds the chance to verify what DS detected, otherwise impossible with the base version...

Arthur R.

**Comment by DrCoffey** [comment]
@rciszek I also want to say a big thanks for making such a cool modification to DeepSqueak.

An alternative option would also be to export the detection file to a Raven table and check the file for missed calls in Raven. You could then import the finalized file back to DeepSqueak for clustering/syntax

**Comment by LWilkinKrug** [comment]
that’s what I used to do, but Screener is a lot faster. 

--
> 

﻿
@rciszek I also want to say a big thanks for making such a cool modification to DeepSqueak.

An alternative option would also be to export the detection file to a Raven table and check the file for missed calls in Raven. You could then import the finalized file back to DeepSqueak for clustering/syntax

**Comment by sailormoonxpower** [comment]
Hello, 

I am new to DeepSqueak and this Screener seems very useful. I am receiving the same error as @LW-Krugie with Matlab2018a. Did anyone figure out how to load detection files that were not created by Screener? 

Thanks!


> @rciszek, it seems it only loads Detection files generated by Screener. Any detection file generated with the base version of DS results in an error
> 
> ```
> Dot indexing is not supported for variables of this type.
> 
> Error in loadcalls_Callback (line 28)
> audio_file_path =  strcat(handles.data.settings.audiofolder,filesep, handles.data.audiodata.AudioFile);
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in DeepSqueak (line 35)
>     gui_mainfcn(gui_State, varargin{:});
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject))
>  
> Error while evaluating UIControl Callback.
> ```

**Comment by LW-Krugie** [comment]
I exported the screener files as Raven files and then imported them into the latest DS. I think it’s the only way to combine data sets created in those two applications.
