### ISSUE TITLE
Training classifier on discriminating calls

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#51]
Hi Kevin,

I have one question that most likely will also resolve the other issue I had posted some time ago with the network training. 

I would like to train a classifier on a type of calls that I record from mouse pups on a given day and on following days. The frequencies are known to change when pups mature. So I was wondering whether I can train a classifier to  be able to discriminate pup calls recorded from pups at age P1 to those recorded at P2.

What is the best way to do this with DeepSqueak?

Thank you,
Isa

**Comment by DrCoffey** [comment]
If the calls are separable by using frequency alone, then I would just use a frequency threshold. 

If you want to use neural networks then you can create a classification network. Load detection files from P1 or P2, add a custom label from the tools menu, then label each call with P1 or P2 (try for ~100 calls each, you might need more).  Then go into tools and train a supervised classifier using the detection files (.mat) that have been saved with the custom labels. Then you can pass new detection files through the classifier to get the labels.

**Comment by imgross** [comment]
The calls are partially separable by frequency but not solely, so in the frequency range there is also some overlap between the two populations.

But thanks very much for that advice, that sounds good, I will try that out.

Thank you,
Isa

**Comment by imgross** [comment]
Hi Kevin,

the classification works now. But I still have two open questions:

1) Is it recommendable to train the classifier with similar numbers of calls per group or does it not matter anymore after a certain number of calls?

2) Is the classifier taking the entire spectrogram into account or a somewhat dimension reduced version of that (like using only a few parameters that are pulled out like principal frequency, duration, etc.)?

Thanks for the help,
Isa

**Comment by DrCoffey** [comment]
The nn classifier uses the spectrogram, not a dimension reduced version of the call (the contour). If you use the k-means style clustering it uses the contour.

I think it should be fine to train with a different number of calls, but I haven't done much testing on it.

**Comment by imgross** [comment]
Great, thanks very much!
