### ISSUE TITLE
Error in export to Excel in 2.6.1

### ISSUE THREAD

**Issue by zpranske** [DrCoffey/DeepSqueak#53]
**Describe the bug**
Hello Dr. Marx and Dr. Coffey,

Thank you for all your work so far on Deepsqueak. For a small percentage of detected call files, I am unable to export the data to Excel. This occurred in the previous version as well -- updating to 2.6.1 resolved the issue for some of the problematic files, but not all. The export process seems to freeze in the same spot on the loading bar every time. This occurs in both the compiled and Matlab versions. The typical error message looks like this:

```
The logical indices contain a true value outside of the array bounds.

Error in CalculateStats (line 37)
stats.ridgeFreq = ridgeFreq(greaterthannoise);

Error in excel_Callback (line 34)
            stats =
            CalculateStats(I,windowsize,noverlap,nfft,rate,box,handles.data.settings.EntropyThreshold,handles.data.settings.AmplitudeThreshold);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('excel_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.
```

I found a similar issue [here](https://github.com/DrCoffey/DeepSqueak/issues/22) that appeared to be resolved by updating, but I have had no such luck. In this case, I did not use a self-trained network but rather the standard Short Rat Call_Network_v2.mat.

**To Reproduce**
With the attached audio/detection files:
1. Go to 'File -> Import/Export -> Export Excel Log (Call Statistics)'
2. Click on Detected call file
3. Loading bar freezes at a given point

**Additional context** 
Operating system: Windows 10 Education
Matlab version: Have tried with 2018b and 2019a, and DS standalone 2.6.1

Thank you,
Zachary Pranske

**Comment by DrCoffey** [comment]
Hey Zachary,

Would you mind sharing an offending detection file? That would make the troubleshooting a bit easier.

-Kevin

**Comment by zpranske** [comment]
Hi Kevin,

Thank you very much for the quick response! I'm attaching it as a Google Drive link because the large size prevents me from uploading it on Github. 

https://drive.google.com/open?id=1YKyG06ZY4Ysw3g_USTdMTfuUAFfy5mkj

-Zachary

**Comment by williamfyke3** [comment]
Hello Dr. Marx and Dr. Coffey,

Was there any resolution to this issue? I am encountering the same problem. Thank you!

- William

**Comment by DrCoffey** [comment]
I was able to export the file without issue. Have you tried updating DeepSqueak to the newest version?

[Set2 6e_Stats.xlsx](https://github.com/DrCoffey/DeepSqueak/files/3947029/Set2.6e_Stats.xlsx)

**Comment by DrCoffey** [comment]
There was a single call in that file with a very tiny box (no idea why). That could be screwing it up?
