### ISSUE TITLE
More statistical options

### ISSUE THREAD

**Issue by bmike1-vt** [DrCoffey/DeepSqueak#56]
Hi,
Would it be possible to add additional statistical variables to the output? Specifically, interval calculation between the vocalization call. This would be of great value!
Thanks

**Comment by DrCoffey** [comment]
Hey,

You can modify the CalculateStats.m function to include anything you like. However, calculating intervals is pretty trivial from the call times, and I would opt to do it during post-hoc analyses. Just read the statistics files into matlab or excel and subtract the previous call time from each call.

-Kevin

**Comment by bmike1-vt** [comment]
Hi Kevin,
This is a great suggestion!  I appreciate this very much.  DeepSqueak has been AWESOME!! We will try to add additional line of code to do more calculation such as entropy.

Thanks and best wishes!
Mike.


[cid:image002.png@01D5579C.A22BC5B0]
Mike Bowers, PhD
Assistant Professor
School of Neuroscience
ILSB,
1981 Kraft Drive
Blacksburg VA 24061 (MC-0913)
540.231.6897 office
540.231.2882 Lab
Bmike1@vt.edu<mailto:Bmike1@vt.edu>

**Comment by DrCoffey** [comment]
Hey Mike,

I believe entropy is related (maybe the inverse?) to the tonality measure we already output. Check the code.

-Kevin
