### ISSUE TITLE
Error when training with existing network

### ISSUE THREAD

**Issue by t-chari** [DrCoffey/DeepSqueak#58]
Hi,

I'm trying to retrain the network as I'm not detecting as many USV calls as I would expect. I'm recording USVs from mouse pups and I'm aware from previous issues that the network hasn't been trained for recording pup vocalizations? It also seems that some USV calls above 80 kHz are missed by the network but I'm not sure if that's the case for calls below 80 kHz. I tried to retrain the existing Mouse Call_Network_V2.mat but get the following error:

_Error using nnet.cnn.LayerGraph>iValidateLayerHasEnoughInputs (line 819)
Layer 'proposalLayer' has 2 connected inputs, but its replacement has 0 inputs.

Error in nnet.cnn.LayerGraph/replaceLayer (line 390)
            iValidateLayerHasEnoughInputs(larray(1), ...

Error in vision.internal.cnn.RCNNLayers.splitFasterIntoFastAndRPN (line 1173)
            frcnn = frcnn.replaceLayer(proposalName,roiInput);

Error in fasterRCNNObjectDetector/getNetworksForAlternateTraining (line 1011)
                [frcnn,rpn,info] = vision.internal.cnn.RCNNLayers.splitFasterIntoFastAndRPN(lgraph);

Error in vision.internal.cnn.parseInputsFasterRCNN (line 113)
    [fastRCNNLayerGraph, rpnLayerGraph,  params.RCNNInfo] = network.getNetworksForAlternateTraining();

Error in trainFasterRCNNObjectDetector (line 333)
    vision.internal.cnn.parseInputsFasterRCNN(...

Error in TrainSqueakDetector (line 61)
detector = trainFasterRCNNObjectDetector(TrainingTables, layers, options, ...

Error in trainnew_Callback (line 39)
        [detector, layers, options] = TrainSqueakDetector(TrainingTables,detector);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('trainnew_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback._

Any help would be much appreciated!

Thanks,
Trish

**Comment by DrCoffey** [comment]
Hey t-chari,

Sorry for the slow response. Which version of Matlab are you using? mathworks keeps changing the way neural networks are trained, so you need to use 2018a. 

https://github.com/DrCoffey/DeepSqueak/wiki/training-detection-networks

If that still doesn't work would you mind sending me a couple files you are using for training, and I will take a closer look.

-Kevin

**Comment by t-chari** [comment]
Hi Kevin,

No worries. Thanks for the input, switching to 2018a seems to have fixed it!

Trish
