### ISSUE TITLE
Keep getting Error in Network

### ISSUE THREAD

**Issue by cvargas4** [DrCoffey/DeepSqueak#6]
I was trying to run DeepSqueak on some of my existing data to see how it works. My recording is 5min and 250kHz sampling. 
After choosing my NN and detection parameters, it starts going through the file, but I will get a series of errors that state they are skipping audio chunks. It inevitably does this for the entire file and nothing is detected. 

```
Warning: Error in Network, Skiping Audio Chunk 
> In SqueakDetect (line 122)
  In multinetdect_Callback (line 93)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
Index exceeds matrix dimensions.

Error in SqueakDetect (line 134)
xmin = AllBoxes(:,1);

Error in multinetdect_Callback (line 93)
            Calls1=SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),0,0,j,length(audioselections),networkname);
            
Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
Error while evaluating UIControl Callback.
```

I used the following parameters in my detection
![image](https://user-images.githubusercontent.com/33707956/48288935-cab71680-e43b-11e8-8ae9-c2e130f4499e.png)

I double checked that Matlab could connect to the GPU, and that doesn't seem to be the issue.

Have these issues been encountered before?
Thanks in advance.

**Comment by DrCoffey** [comment]
What version of matlab are you using? The "MouseCall_HighSensitivity" network was trained with matlab 2018. I'm not sure, but it could be the case that networks trained with 2018 are not compatible with 2017. Does the same thing happen with the other "MouseCall" network?

-Russell

**Comment by DrCoffey** [comment]
No worries, glad you got it worked out.
