### ISSUE TITLE
Adding 12+ Call Classifications

### ISSUE THREAD

**Issue by Cesarmedina123** [DrCoffey/DeepSqueak#60]
I would like to add more than 12 call classifications as labels, however, I am capped at 12 and cannot find the matlab file where this is designated. Is it possible to change the number of possible labels to over 12 and if so what's the name of the matlab file?

**Comment by DrCoffey** [comment]
Hey,

The function is in the main DeepSqueak.m code - 

function customlabels_Callback(hObject, eventdata, handles)
% Define call categories
prompt = {
    'Label 1  --- Key 1'
    'Label 2  --- Key 2'
    'Label 3  --- Key 3'
    'Label 4  --- Key 4'
    'Label 5  --- Key 5'
    'Label 6  --- Key 6'
    'Label 7  --- Key 7'
    'Label 8  --- Key 8'
    'Label 9  --- Key 9'
    'Label 10  --- Key 0'
    'Label 11  --- Key -'
    'Label 12  --- Key ='
    };
dlg_title = 'Set Custom Label Names';
num_lines=[1,60]; options.Resize='off'; options.WindowStyle='modal'; options.Interpreter='tex';
old_labels = handles.data.settings.labels;
new_labels = inputdlg(prompt,dlg_title,num_lines,old_labels,options);
if ~isempty(new_labels)
    handles.data.settings.labels = new_labels;
    handles.data.saveSettings();
    update_folders(hObject, eventdata, handles);
end
guidata(hObject, handles);

You should be able to add more labels to this section of the code, and the corresponding keyboard shortcut.

**Comment by Cesarmedina123** [comment]
Thank you! On a related note, I was unable to reproduce the 20 novel call categories that you identified in your original publication using the supervised classification schemes included in the DeepSqueak package such as the "WrightClassifierNet" or "MeanClassifierNet". This occurred despite running hundreds of call files [did not make sure that I had all types of calls present in those files to begin with] through the classifiers. Are the 20 novel call categories saved into one of the classifiers already and I just don't have enough of each call for the net to accurately classify [under sampling]?

**Comment by DrCoffey** [comment]
The 20 novel categories were generated using the unsupervised k-means approach, and they are specific to a particular data set of mouse USVs. The "k-means optimized" approach only uses information from the exact data set being analyzed. The neural networks like the WrightClassifierNet are meant to classify your calls based on previous datasets. In the case of the WrightClassifierNet it is based on Rat USV classifications from Wright et al's work with amphetamine induced USVs.
