### ISSUE TITLE
Error in Network, Skiping Audio Chunk

### ISSUE THREAD

**Issue by ele-meni** [DrCoffey/DeepSqueak#63]
When I first start DeepSqueak with Matlab 2019b (on MacOS 10.14.6) I get the following

```
Error in Network, Skiping Audio Chunk
Warning: Error using vision.internal.cnn.validation.checkImageAndNetworkChannelSizes (line 8)
Invalid input image channel size: 1.

The input image channel size (1) must be the same as the network's input channel size (1).

Error in vision.internal.cnn.utils.convertImageToMatchNumberOfNetworkChannels (line 30)
            vision.internal.cnn.validation.checkImageAndNetworkChannelSizes(...

Error in fasterRCNNObjectDetector>iPreprocess (line 1742)
    Iroi = vision.internal.cnn.utils.convertImageToMatchNumberOfNetworkChannels({Iroi}, colorPreprocessing);

Error in fasterRCNNObjectDetector/detect (line 538)
                Iroi = iPreprocess(I, roi, useROI, colorPreprocessing);

Error in SqueakDetect (line 120)
            [bboxes, scores, Class] = detect(network, im2uint8(im), 'ExecutionEnvironment','auto','NumStrongestRegions',Inf);

Error in multinetdect_Callback (line 77)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0) 
> In SqueakDetect (line 168)
  In multinetdect_Callback (line 77)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),0) 
```

**Comment by DrCoffey** [comment]
Hey ele-meni,

I haven't encoutered this exact issue, but Error in Network, Skiping Audio Chunk usually means there is something wrong with the audio issue. It may also be an issue with the Mac version of 2019b.

Can you share an offending file through google drive so I can take a look.

**Comment by ele-meni** [comment]
This happens with the example Mouse and Rat recordings

**Comment by DrCoffey** [comment]
Do you have all of the required toolboxes?

Required Matlab toolboxes:

Computer Vision System Toolbox™
Curve Fitting Toolbox™
Image Processing Toolbox™
Deep Learning Toolbox™ (formerly Neural Network Toolbox™)
Parallel Computing Toolbox™

The error is very odd:

"Invalid input image channel size: 1.

The input image channel size (1) must be the same as the network's input channel size (1)."

It seems to be saying the image and network are bot size==1, but also that they are different...

**Comment by ele-meni** [comment]
Yes and as a control I don't get warnings about missing toolboxes when I launch the GUI. I am not sure as I get this error with default settings, is there something I have to modify which I am missing?

**Comment by gutzcha** [comment]
I have also encountered this problem, and got the same error report.

I also tried to run it on the example Rat recordings with the same results, so i don't think that the audio file is the problem.

I have MATLAB R2019b  can this be the cause?

**Comment by jenday** [comment]
Has anyone figured this out? I get the same error with DeepSqueak with Matlab 2019b (on MacOS 10.14.6)!

**Comment by DrCoffey** [comment]
It seems like this is a Mac specific problem and we can't seem to figure it out. DeepSqueak has worked on Macs before so I am not sure what happened. We will look into it when we find time, but that is pretty short these days, sorry.

**Comment by PhDcd** [comment]
Has anyone had success on a Mac with MATLAB 2018a or 2018b?

**Comment by LWilkinKrug** [comment]
Yes, I’ve been using both, although, for network training, I recommend 2018a

**Comment by victorromeo** [comment]
This issue is also apparent in 2019b on Ubuntu 18.04.  (Installed locally, not globally)

Can confirm my wav audio files load fine with Audacity, and error in Deep Squeak occurs regardless which file is selected.

**Comment by Tranquilo66** [comment]
Hi,

I have the same issue on 2019b, on WIN10 System.

It looks like the error is generated in this matlab function called:

**function checkImageAndNetworkChannelSizes**(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

_[~, ~, Isize] = size(I);

if ndims(I) ~= 3 || Isize ~= networkChannelSize
    error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end_

AND the point is that the ndims(I) is 2 instead of 3 for an RGB image

I tried the audio file: "Example Mouse Recording.flac" and the dimension of I for
this audio file is 187 x 3887 unit8.
I guess this is not a valid RGB file..

This might be the reason why the DeepSqueak becomes silent ?

**Comment by Tranquilo66** [comment]
Hi,

update: everything works FINE with an older matlab release:

I used: 

MATLAB Version: 9.4.0.813654 (R2018a)

Now it works.

**Comment by DrCoffey** [comment]
I finally found the issue, and Mathworks is indeed responsible!  They broke all monochrome cnn detection! Any image that is not 3 channels will throw an error. Luckily it is an easy fix. You need to change the file permissions to edit core functions.
Change this file:
MATLAB\R2019b\toolbox\vision\vision\+vision\+internal\+cnn\+validation\checkImageAndNetworkChannelSizes.m
From this:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3 || Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
To This:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3
if Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
end
