### ISSUE TITLE
Error loading detected calls via Long_Rat_Call_Network_V2

### ISSUE THREAD

**Issue by jomaksic** [DrCoffey/DeepSqueak#64]
Hi!

I'm using the 2018b Matlab version on Windows 10.

I have been using the Long_Rat_Call_Network_V2 to detect (mostly) successfully over the last couple of weeks. The only time I've gotten an error was when there weren't any calls actually present in the .wav file (which makes sense). However, for the last couple of files, I have been getting an error when trying to use the Long Rat_Call_Network_V2 for detection, even though there definitely are calls present in the file. Basically the .mat detection file is created, but I am unable to load it. I have tried using the Short Rat_Call_Network_V2 which does work, however it also detects a lot of noise and double (or tripple) counts the calls since they are longer. 

I have been using the same set of parameters for all previous detections, and it has worked fine. There shouldn't be a difference in the file itself, so the error is a bit odd.

I'm attaching screenshots here:

![dsscrnshot1](https://user-images.githubusercontent.com/57396794/68205964-d9db9080-ffcb-11e9-93c1-c7117a7e9910.PNG) (the parameters used)

![dsscrnshot2](https://user-images.githubusercontent.com/57396794/68206019-fe376d00-ffcb-11e9-89e5-eac8d18f5666.PNG) (the error after trying to load the calls)

![dsscrnshot3](https://user-images.githubusercontent.com/57396794/68206034-068fa800-ffcc-11e9-8afd-8a09e547ecc0.PNG) ...and the code 

Perhaps this issue has already been raised, but my programming skills aren't very advanced so I wasn't sure! 

Thank you in advance :)

**Comment by DrCoffey** [comment]
Hey, I'm not exactly sure what is going on. Would you mind sharing the an offending wav file or detection file so I can take a look? Emailing a google drive link usually works best. 

Also, when I run the long-call networks, I generally set the high frequency cut-off to ~35-40kHZ. If you have mixed short and long calls, you can use multi-detect to pick a short call network too, and then  only look from 35-85. That will prevent the short call network from detecting all of the long calls.

**Comment by jomaksic** [comment]
Hi,

Thank you so much for the advice! Will try playing with multi-detect then.

I'm attaching the usv file here.
 usv_014_Aligned.wav
<https://drive.google.com/a/nyu.edu/file/d/1j4GFMPXmscc4QV5l4AcqXb_RSS9vw8Nd/view?usp=drive_web>

On Fri, Nov 8, 2019 at 12:01 AM DrCoffey <notifications@github.com> wrote:

> Hey, I'm not exactly sure what is going on. Would you mind sharing the an
> offending wav file or detection file so I can take a look? Emailing a
> google drive link usually works best.
>
> Also, when I run the long-call networks, I generally set the high
> frequency cut-off to ~35-40kHZ. If you have mixed short and long calls, you
> can use multi-detect to pick a short call network too, and then only look
> from 35-85. That will prevent the short call network from detecting all of
> the long calls.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DrCoffey_DeepSqueak_issues_64-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANV44OQAVGAVZPJ23PTYE3TQSSM4NA5CNFSM4JJBUYQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDOEFRI-23issuecomment-2D551305925&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=rmNcFEV3EwA8mAzK1tW9xg&m=vr0gph4h9G3V_QImOPQGd17U4rQec3CNhXUGkgV2IpA&s=ibh5COm-d0k0Mrpu0voW_X4jtRALchYbE64mUSKu77s&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANV44OVPWOYA4I3RPCMY7PTQSSM4NANCNFSM4JJBUYQQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=rmNcFEV3EwA8mAzK1tW9xg&m=vr0gph4h9G3V_QImOPQGd17U4rQec3CNhXUGkgV2IpA&s=FEPcNAiYaNzS-K10vwKYxwNRMoOdC0EaPsLlIbCyMnM&e=>
> .
>


-- 
*Jovana Maksic*
New York University Shanghai  '18
Neuroscience

**Comment by DrCoffey** [comment]
Hey,

Was able to detect and load these calls by lowering the time chunck to 4s and only looking from 18kHZ to 45kHZ. You have a lot of noise in that band as well, but it is very easily removed with a power threshold (reject below -80dB)
