### ISSUE TITLE
Lowering threshold

### ISSUE THREAD

**Issue by PhDcd** [DrCoffey/DeepSqueak#67]
I get a warning stating "Upper range above sampling frequency" and then a ton of lines of "Lowering threshold" -- I assume the first means that my audio file doesn't have calls that reach the maximum frequency set... but I am wondering what the lowering threshold means
<img width="961" alt="LT" src="https://user-images.githubusercontent.com/58785213/70940940-65a7fa00-2019-11ea-950a-c95df01c3aae.png">

**Comment by DrCoffey** [comment]
That is for contour extraction. The threshold is set by a slider in the lower left by the tonalilty graph. If a call is not very tonal (whistle like) it will try to auto lower the threshold so it can extract something. Is it breaking anything, or just a warning?

**Comment by PhDcd** [comment]
I think it might just be a warning... I am getting a lot of "calls" that look like the attached pictures
<img width="1101" alt="SS1" src="https://user-images.githubusercontent.com/58785213/71008501-b883bf00-20b6-11ea-813c-d60963285d06.png">
<img width="1040" alt="SS2" src="https://user-images.githubusercontent.com/58785213/71008508-b9b4ec00-20b6-11ea-93ad-500edd22dde3.png">

. I have been rejecting them because I believe they are just catching the consistent background noise of the air circulation unit in the lab.
I also would like to say I appreciate your prompt feedback and your patience with me-- this is all new to me.  Do you have other papers you would recommend that would help with my understanding of rat US calls?

**Comment by DrCoffey** [comment]
Hey, rats do make long 22 kHz alarm calls, but those look a little too perfect. You could try to use the long-call network and see if the ends trail up or down. It also looks like you are only recording at 94kHZ. Many rat and mouse calls can go up to 100 kHz, so you need to record at double that frequency. Generally I aim for 250 kHz.

**Comment by PhDcd** [comment]
So, the straight line I think is this constant background noise from an air circulation system. But, if I do the Post Hoc denoising as instructed, I lose almost all calls. I have some detections of actual 18-24kHz calls
<img width="971" alt="ss4" src="https://user-images.githubusercontent.com/58785213/71031279-10372000-20e1-11ea-9f5e-5e5481142056.png">
<img width="828" alt="ss5" src="https://user-images.githubusercontent.com/58785213/71031284-11684d00-20e1-11ea-9a2b-d6180b10bc83.png">

I am only looking at distress calls, so should I still increase my recording kHz?

**Comment by DrCoffey** [comment]
You could use some of the "dumb" noise removal tools "Tools > Automatic Review > Batch Reject by Threshold". Then find some metric where the noise is different then the calls. Honestly, the best option is to remove the noise source from the room. Look at the spectrometer live and go around turning off equipment, lights, etc until you find the noise source. Then find a way to isolate the recording from the noise. While DeepSqueak is really good at dealing with most noise sources, having a loud consistent noise band in the range of your USVs is never a good idea.

**Comment by VoiceScientist** [comment]
I've had some success using foam or cloth to block the ultrasonic noise coming from the air conditioning - sort of rig up a sound booth of sorts. That narrow band of noise could be from a computer monitor as well. Try recording with and without the monitor on. Alternatively, your noise looks narrow band and your USVs in the screen shots are lower than the noise, so you could just use a low-pass filter to remove it. A quick Praat batch script could take care of all your files quickly:
http://www.fon.hum.uva.nl/praat/manual/Filtering.html
http://phonetics.linguistics.ucla.edu/facilities/acoustic/LowPassFilter.txt

**Comment by LWilkinKrug** [comment]
I’ve built a soundproof chamber as well but, unfortunately, I’m still getting the 60kHz line. I think it’s our facility’s central aircon, so not something easily turned off.

**Comment by PhDcd** [comment]
I have the same issue, its not a sound I can get rid of and I am video recording rat behavior as well, so it is difficult to use foam or cloth to block the sound.  I do have a clear plexiglas lid but it may be causing some resounding in my recordings.  Thanks for the feedback everyone!
