### ISSUE TITLE
Error loading saved detection .mat files

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#68]
After detecting calls with a trained network and editing some of the boxes with saving the file inbetween I run it through a classification network. 

However for the classification to work the .mat needs to be loaded in, which fails.

This sometimes happens to me and I do not know why this occurs. When I try just loading the .mat file into Matlab by drag and drop this gives me also an error message saying cannot load file X. 

This is the error message that pops up:

Error using load
Cannot read file I:\Isa Maria Gross\Miniscope\cohort
1\IG_180412a\Data\awk-2018-05-24\PR\1\audio\IG_180412a0002_2merge.mat.

Error in loadCallfile (line 2)
load(filename, 'Calls');

Error in loadcalls_Callback (line 12)
handles.data.calls = loadCallfile(fullfile(handles.detectionfiles(handles.current_file_id).folder,
handles.current_detection_file));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

Do you have a solution for me to rescue that file?

Cheers,
Isa

**Comment by DrCoffey** [comment]
Hey Isa,

I've never seen this, can you send a broken file?

-Kevin

**Comment by imgross** [comment]
Hi Kevin,

yes, sure. How should I send it best?

Cheers,
Isa
