### ISSUE TITLE
Unsupervised clustering: Warning

### ISSUE THREAD

**Issue by LW-Krugie** [DrCoffey/DeepSqueak#69]
Hey Kevin, 

I get the following warning when using unsupervised clustering (elbow)

`Warning: Failed to converge in 100 iterations. 
> In kmeans/loopBody (line 474)
  In internal.stats.parallel.smartForReduce (line 136)
  In kmeans (line 343)
  In kmeans_opt (line 59)
  In UnsupervisedClustering_Callback (line 64)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('UnsupervisedClustering_Callback',hObject,eventdata,guidata(hObject)) `

The clustering works, but I'd like to know what the warning means. 

Cheers

LK

__
Operating system / MATLAB version
Mac OS Catalina 10.15.2 / 2018a

**Comment by DrCoffey** [comment]
Hey,

kmeans_opt runs kmeans many many times. I believe this shows up when an individual instance of calling kmeans doesn't converge. As long as it landed on a solution it should be fine.

-Kevin

**Comment by LW-Krugie** [comment]
awesome, thanks Kevin
