### ISSUE TITLE
Number of total vocalization+vocalization per time unit

### ISSUE THREAD

**Issue by gidikarmon** [DrCoffey/DeepSqueak#71]
Hi all,
Is it possible to get total number of calls per recording and per time point?

For example- I recorded mice for 6 min and I would like to get the total number of calls as well as number of call in min 1, min 2, min 3 etc..

Thanks!
Gidi

**Comment by DrCoffey** [comment]
Hey Gidi,

DeepSqueak is only meant for detection, clustering, and syntax analysis. Basically all of the pre-processing. To analyse USVs and their relationship to behavior you will need to output the statistics tables and do post-processing on your own. 

Here are the export instructions: https://github.com/DrCoffey/DeepSqueak/wiki/export-to-excel

**Comment by gidikarmon** [comment]
Thanks,
If I knew how to code in Matlab I would add it myself. I imagine its quite easy.


Anyway Thank you!
