### ISSUE TITLE
What is the difference between the different clustering models?

### ISSUE THREAD

**Issue by gidikarmon** [DrCoffey/DeepSqueak#72]
Hi,
I am looking to classify USV from mouse pups in response to separation from their mother, which clustering model should I use and what is the difference between them?

Thanks,
Gidi

**Comment by LW-Krugie** [comment]
Hi Gidi,

I’ve been working on clustering rat pup USVs and it seems that none of the available models works well. We are currently investigating options to train a new model, but that’ll likely involve manually categorising individual calls.

Let me know how you get on.

Krugie

On 19/01/2020, at 8:56 PM, gidikarmon <notifications@github.com> wrote:

Hi,
I am looking to classify USV from mouse pups in response to separation from their mother, which clustering model should I use and what is the difference between them?

Thanks,
Gidi

**Comment by DrCoffey** [comment]
None of the pre-trained models were made with pup calls.

I would try the unsupervised "k-means" clustering. Use all of your detection files at once to improve the accuracy.

https://github.com/DrCoffey/DeepSqueak/wiki/unsupervised-clustering
