### ISSUE TITLE
Error Messages after "Detect Calls"

### ISSUE THREAD

**Issue by DraysonCampbell** [DrCoffey/DeepSqueak#73]
Apologies if this should be a straightforward fix... I am new to DeepSqueak and a relative beginner on MATLAB. 

I load DeepSqueak (all packages installed) and select a .wav file. When I click "detect calls", the network loads, and then says that there is an error. The following code repeatedly appears (10-100+ times) in the MATLAB output. 
At the end of the file, DeepSqueak says that there are no calls detected in my file, however, I know this not to be the case as I have manually checked the .wav file several times already. 

Error in Network, Skiping Audio Chunk
Warning: Error using vision.internal.cnn.validation.checkImageAndNetworkChannelSizes
(line 8)
Invalid input image channel size: 1.

The input image channel size (1) must be the same as the network's input channel size
(1).

Error in vision.internal.cnn.utils.convertImageToMatchNumberOfNetworkChannels (line 30)
            vision.internal.cnn.validation.checkImageAndNetworkChannelSizes(...

Error in fasterRCNNObjectDetector>iPreprocess (line 1742)
    Iroi = vision.internal.cnn.utils.convertImageToMatchNumberOfNetworkChannels({Iroi},
    colorPreprocessing);

Error in fasterRCNNObjectDetector/detect (line 538)
                Iroi = iPreprocess(I, roi, useROI, colorPreprocessing);

Error in SqueakDetect (line 120)
            [bboxes, scores, Class] = detect(network, im2uint8(im),
            'ExecutionEnvironment','auto','NumStrongestRegions',Inf);

Error in multinetdect_Callback (line 77)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
> In SqueakDetect (line 168)
  In multinetdect_Callback (line 77)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 

Thank You for your help.

**Comment by katycelina** [comment]
I've had the same issue using MATLAB 2019a. It worked fine when I was using MATLAB 2018, but there's no way for me to get 2018 from my university anymore. Is there an updated version coming soon?

Thanks

**Comment by uoftstudent215** [comment]
I've had the same issue as well! Were you able to figure out what the problem is? 
I have all the required toolboxes downloaded and played around with different values before clicking detect calls, but would always end up with the same error saying my audio file is empty.

**Comment by DrCoffey** [comment]
Hey All,

Sorry we have been very busy with other projects. It looks like Mathworks made some changes that broke DeepSqueak in 2019b. We aren't sure what they are yet, but I will try to look into it soon.

Everything still works in the old version, and a MATLAB licence should be version independent.

https://www.mathworks.com/downloads/web_downloads/download_release?release=R2018b

-Kevin

**Comment by katycelina** [comment]
Thank you! It works now :)

**Comment by DrCoffey** [comment]
I finally found the issue, and Mathworks is indeed responsible!  They broke all monochrome cnn detection! Any image that is not 3 channels will throw an error. Luckily it is an easy fix. You need to change the file permissions to edit core functions.
Change this file:
MATLAB\R2019b\toolbox\vision\vision\+vision\+internal\+cnn\+validation\checkImageAndNetworkChannelSizes.m
From this:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3 || Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
To This:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3
if Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
end
