### ISSUE TITLE
Error in Network, Skiping Audio Chunk

### ISSUE THREAD

**Issue by Makenzlietaylor** [DrCoffey/DeepSqueak#74]
We are having an network error message after we have moved to the new matlab R2019b. 
Bellow is the error message:

Error in Network, Skiping Audio Chunk
Warning: Error using
vision.internal.cnn.validation.checkImageAndNetworkChannelSizes
(line 8)
Invalid input image channel size: 1.

The input image channel size (1) must be the same as the network's
input channel size (1).

Error in
vision.internal.cnn.utils.convertImageToMatchNumberOfNetworkChannels
(line 30)
            vision.internal.cnn.validation.checkImageAndNetworkChannelSizes(...

Error in fasterRCNNObjectDetector>iPreprocess (line 1742)
    Iroi =
    vision.internal.cnn.utils.convertImageToMatchNumberOfNetworkChannels({Iroi},
    colorPreprocessing);

Error in fasterRCNNObjectDetector/detect (line 538)
                Iroi = iPreprocess(I, roi, useROI,
                colorPreprocessing);

Error in SqueakDetect (line 120)
            [bboxes, scores, Class] = detect(network,
            im2uint8(im),
            'ExecutionEnvironment','auto','NumStrongestRegions',Inf);

Error in multinetdect_Callback (line 77)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

**Comment by DrCoffey** [comment]
Ya, Matlab has changed something and we haven't had time to figure it out yet. Stick with an older version for now.

**Comment by DrCoffey** [comment]
I finally found the issue, and Mathworks is indeed responsible!  They broke all monochrome cnn detection! Any image that is not 3 channels will throw an error. Luckily it is an easy fix. You need to change the file permissions to edit core functions.
Change this file:
MATLAB\R2019b\toolbox\vision\vision\+vision\+internal\+cnn\+validation\checkImageAndNetworkChannelSizes.m
From this:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3 || Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
To This:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3
if Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
end

**Comment by victorromeo** [comment]
That particular work around is not working for me on Ubuntu 18.04 with Matlab R2019b Update 3. It continues to show **Error in Network, Skiping Audio Chunk** when running 'Detect Calls' on DeepSqueak

**Comment by bhimbbiswa** [comment]
Hi, I am also getting the same error in Matlab R2020a.

In this version code is different.

"""
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize, ~] = size(I);

if Isize ~= networkChannelSize
    error(message('vision:ObjectDetector:invalidInputImageChannelSize', Isize, networkChannelSize));
end

"""

Can you please guide me on what to do.

**Comment by bhimbbiswa** [comment]
This is the error message I am getting.

`
Error in Network, Skiping Audio Chunk
Warning: Index exceeds the number of array elements (2).

Error in fasterRCNNObjectDetector/detect (line 557)
                updateNetworkIfRequired(this,params.ImageSize(1:3),params);

Error in SqueakDetect (line 120)
            [bboxes, scores, Class] = detect(network, im2uint8(im), 'ExecutionEnvironment','auto','NumStrongestRegions',Inf);

Error in multinetdect_Callback (line 77)
        Calls = [Calls; SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
> In SqueakDetect (line 168)
  In multinetdect_Callback (line 77)
  In gui_mainfcn (line 95)
  In DeepSqueak (line 30)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
No Calls found in: C15.27.4. A

`

**Comment by bhimbbiswa** [comment]
This is the error message I am getting.

Error in Network, Skiping Audio Chunk
Warning: Index exceeds the number of array elements (2).

Error in fasterRCNNObjectDetector/detect (line 557)
updateNetworkIfRequired(this,params.ImageSize(1:3),params);

Error in SqueakDetect (line 120)
[bboxes, scores, Class] = detect(network, im2uint8(im), 'ExecutionEnvironment','auto','NumStrongestRegions',Inf);

Error in multinetdect_Callback (line 77)
Calls = [Calls; SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
feval(varargin{:});

Error in DeepSqueak (line 30)
gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)

In SqueakDetect (line 168)
In multinetdect_Callback (line 77)
In gui_mainfcn (line 95)
In DeepSqueak (line 30)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
No Calls found in: C15.27.4. A

**Comment by bhimbbiswa** [comment]
Hi Dr Coffey,

Any clue how to rectify this error. 

I will greatly appreciate your help.

Regards,

Bhim
