### ISSUE TITLE
Some Cluster-Types apparently Excluded

### ISSUE THREAD

**Issue by GabrielStahl** [DrCoffey/DeepSqueak#75]
Dear DeepSqueak-Team, 

We used unsupervised clustering and the k-means method to determine clusters. 
This yielded 22 clusters, which we could review via "view clusters". 

Our issue: When searching through the files where the "Type" (i.e. the cluster the vocalisation belongs to) is saved, some cluster-types are not present anymore. 

Is there a threshold of how many members a given cluster must contain so that the cluster is used when saving? And if yes, in which file should I search for this piece of code to omit this threshold?

Looking forward to your kind support!
Best wishes, 
Gabriel

**Comment by DrCoffey** [comment]
Hey Gabriel,

If you performed clustering on many files then not all of them will necessarily contain every type. Are some types being excluded from every file? 

-Kevin

**Comment by GabrielStahl** [comment]
You are right, it was the case that all types are present in at least some of the files. 

Thank you for the quick and helpful answer!
