### ISSUE TITLE
Issue with network training 

### ISSUE THREAD

**Issue by ad2468** [DrCoffey/DeepSqueak#78]
Hi!

I'm trying to use DeepSqueak to identify mouse pup USVs. So far the program has been incredibly helpful and easy to use - thank you! Both the mouse call network and the short call network do a pretty good job, and I'm hoping to use some of our data to train these existing networks to better identify calls in our data. 

I'm having an issue with the network training. I'm able to create the image tables, but then when I try to do the network training I'm getting the following error: 

Can't reload '/Applications/MATLAB_R2018a.app/bin/maci64/libmwgpu.dylib'

Error in nnet.internal.cnn.util.isGPUCompatible (line 9)
if(iCanUsePCT() && parallel.gpu.GPUDevice.isAvailable())

Error in nnet.internal.cnn.util.GPUShouldBeUsed (line 17)
        tf = nnet.internal.cnn.util.isGPUCompatible();

Error in vision.internal.cnn.parseInputsFasterRCNN>iCheckExecutionEnvironment (line 466)
nnet.internal.cnn.util.GPUShouldBeUsed(env, []);

Error in vision.internal.cnn.parseInputsFasterRCNN (line 16)
iCheckExecutionEnvironment(options);

Error in trainFasterRCNNObjectDetector (line 261)
    vision.internal.cnn.parseInputsFasterRCNN(...

Error in TrainSqueakDetector (line 61)
detector = trainFasterRCNNObjectDetector(TrainingTables, layers, options, ...

Error in trainnew_Callback (line 41)
        [detector, layers, options] = TrainSqueakDetector(TrainingTables);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('trainnew_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

It seems like it's something to do with the computer's GPU? I'm running MatLab 2018a on a relatively old Mac desktop (OS X). The graphic card is a NVIDIA GeForce GT 755M, if that's helpful at all. 

Thank you so much for your help, and please let me know what additional information I can provide! 

Amy

**Comment by ad2468** [comment]
Hi,

I switched to a different computer and the training is working now! It's been really effective, and I've got a trained network that's very reliably recognizing the calls in our (noisy!) recordings.

Thank you so much!
Amy
________________________________

**Comment by DrCoffey** [comment]
Ok great! If you ever feel like sharing your "pup call" network let me know and I'll add it to the official build.

No pressure though, I understand these things take energy produce and need to be used in-house  first.

-Kevin
