### ISSUE TITLE
Supervised classification error

### ISSUE THREAD

**Issue by lauren546** [DrCoffey/DeepSqueak#80]
Hi Dr. Coffey,

I've been using a supervised classification that I trained from detections on my work computer (which is currently unavailable to me). Luckily I had the classification network file on my dropbox, so I am attempting to use it to run classifications from home. I'm running into an error "Unrecognized method, property, or field 'loadCalls' for class 'squeakData'.", which I think might have something to do with various updates since I made the classification network.

I was just curious if you had any insights on how I might be able to fix this or if I'm out of luck for now.

-Lauren

**Comment by lauren546** [comment]
I fixed the issue! I needed to use one of the different versions of the code

**Comment by DrCoffey** [comment]
Ok great.
