### ISSUE TITLE
Display of the full loaded calls

### ISSUE THREAD

**Issue by micky-lab** [DrCoffey/DeepSqueak#81]
Hi:

I am using deepsqueak for the analyses of rats' USV, usually recorded during a 20 min behavioral test.
After I run Deepsqueak I am able to load a call file and check/redraw/reject all the detected call withing the files which is great.

Nevertheless I would like to be able to visualize the entire loaded call file in the display such that I can visually check if some have been missed or not.
To my knowledge this is not possible as the "Change Display Range" option is only targeted to the visualization of a detected/selected call.

Is there a way that the "Change Display Range" be applied to the entire loaded call file?
such that I could scroll/zoom in/out over the entire file and look for some missing calls,

Thanks,
Steve.

**Comment by DrCoffey** [comment]
That is not currently supported in DeepSqueak, however another group has a fork called DeepSqueak Screener, which does exactly what you are looking for. 

https://github.com/UEFepilepsyAIVI/DeepSqueak
