### ISSUE TITLE
Error in Network, Skipping Audio Chunk

### ISSUE THREAD

**Issue by AbyFlores** [DrCoffey/DeepSqueak#82]
While trying to run "Detect Calls" from the DeepSqueak GUI, I got the following error read out from my Matlab console. I tried both on long and short rat call_network_V2.mat. This audio file had previously worked on another computer with Matlab-DeepSqueak. 

I have also attached here the toolboxes I downloaded in case I may have missed something.  

![DeepSqueak issue](https://user-images.githubusercontent.com/63807560/79487151-a6664e80-7fcc-11ea-8bb1-b6faf7247a37.JPG)
![MATtools](https://user-images.githubusercontent.com/63807560/79487163-a9f9d580-7fcc-11ea-9087-a533832975f7.JPG)

*I did check, and I do have Parallel Computing Toolbox (It is called Parallel Processing in the install start-up)

**Comment by AbyFlores** [comment]
I tried both on long and short rat call_network_V2.mat. This audio file had previously worked on another computer with Matlab-DeepSqueak.

**Comment by bhimbbiswa** [comment]
I am also getting the exact same error in MATLAB R2020a. I have all the required toolbox.

**Comment by eringiglio** [comment]
Same! I'm glad to know it isn't just me; I'm running a set of files that was previously run through Deep Squeak by a colleague perfectly well and was thinking it might be something I was doing. I am also running in Matlab 2020a.

**Comment by raettchen** [comment]
Same here in 2017b. I have all the required toolbox.
I looked up closed issues for the similar error. In 2017b, there is no checkImageAndNetworkChannelSizes.m in vision.

The error location is here slightly different.

![image](https://user-images.githubusercontent.com/64027637/79770862-40602b00-832e-11ea-8500-d8460a2e453c.png)

**Comment by eringiglio** [comment]
Technically DeepSqueak is only supposed to be run in Matlab 2018a or later, which might be the source of that problem, @raettchen? Cf the wiki [here](https://github.com/DrCoffey/DeepSqueak/wiki/Installation). 

But also I'm kind of glad you tried running it on 2017b before I could spend all day trying to reinstall Matlab 2019a and all the requisite toolboxes to check.

**Comment by raettchen** [comment]
Oh I see. As README says it was tested in 2017b, I thought it would work. Thanks.

**Comment by eringiglio** [comment]
@AbyFlores Are you running Matlab 2020a also?

**Comment by raettchen** [comment]
I have only 2017b at the moment.

**Comment by eringiglio** [comment]
I mean, it's also possible that there was an update rolled out that has made things nonfunctional. 

I'm going to try and check on Matlab 2019a, I think I have an installation on another machine.

**Comment by eringiglio** [comment]
Aaaaand it works fine in Matlab 2019a. So that's the underlying issue, I think.

**Comment by AbyFlores** [comment]
> @AbyFlores Are you running Matlab 2020a also?

@eringiglio: Yes, I am also running on Matlab2020a.

**Comment by eringiglio** [comment]
I'm going to guess it's some kind of issue with Matlab 2020a, then. I'm having good success in Matlab 2019a, which is incredibly obnoxious but might be a useful (hopefully temporary) workaround.

**Comment by DrCoffey** [comment]
Hey All,

I am so sorry for the confusion. DeepSqueak will only run in Matlab 2018a, 2018b, and 2019a. 

Mathworks broke monochrome networks in 2019b. Basically they check the network size and throw an error if it isn't RGB. I alerted them to the problem and even coded the fix. They said they were on it, but they decided to code the fix themselves and it is still coded wrong... I understand the your frustration because I am also pissed lol. I have put in another request to fix it...

-Kevin

**Comment by DrCoffey** [comment]
This is the second time Mathworks has broken monochrome network function. It will work completely fine with the following fix.

Offending File: "\MATLAB\R2020a\toolbox\vision\vision\fasterRCNNObjectDetector.m"          

Offending Line 557: updateNetworkIfRequired(this,params.ImageSize(1:3),params);

Replacement Lines:
try
updateNetworkIfRequired(this,params.ImageSize(1:3),params); 
catch 
updateNetworkIfRequired(this,params.ImageSize(1:2),params);
end   

That should fix DeepSqueak in 2020a

**Comment by AbyFlores** [comment]
Hello, everyone! 

Thank you for the assistance!! :)

**Comment by oxynmr** [comment]
Hello everyone, 

Has anyone encountered the same issue with Matlab2023a? 

For 2023a, NetworkIfRequired(this,params.ImageSize,params) does not have specified params.().
Can specifying parameters < try (1:3) catch (1:2) > still works?

Regards.
