### ISSUE TITLE
Differences between 2018a and 2019a Matlab running DS

### ISSUE THREAD

**Issue by AbyFlores** [DrCoffey/DeepSqueak#85]
I've noticed differences in the detect calls function between 2018 vs 2019 Matlab for DeepSqueak. Using the same starting parameters and network (short rat calls), the 2018 version is more permissive and detects more calls and noise. The calls missed by the 2019 version tend to be sub 30kHz or surrounded by noise.   

I was wondering what may account for these differences? Is there a way I can alter 2019 version so to allow for more calls? I'd be happy to share some sample data to illustrate my point further.

**Comment by DrCoffey** [comment]
That sounds odd. Mathworks is always changing code that DeepSqueak relies on, so I'm not totally surprised. Can you send an example for me to play with. It might take me a while to get to it, I'm stretched pretty thin between my lab work and organizing/protesting.

**Comment by AbyFlores** [comment]
Hi Dr. Coffey,

I apologize for the delay - I've also been preoccupied with other lab
work, classes, and organizing/protesting. I'm glad that you're also making
time to take a stand.

Thank you for getting back to me. After talking to my PI, he prefers if I
pursue this question at a later date. I will respond back to this thread
when the time comes.

Again, thank you for your time.

Sincerely, Aby Flores
