### ISSUE TITLE
Difference between .mat and .xlsx. output

### ISSUE THREAD

**Issue by imgross** [DrCoffey/DeepSqueak#87]
Hi there,

is it correct that there is a difference in the output of the .mat file and the exported .xlsx file that you get after detection?

Specifically I am referring to the timing of the detected calls. The parameters found under 'Box' for the .mat file give you the timing of the call within the entire audio file, as far as I understood. So in principal they should be the same as the timing you get when exporting to an excel file, right?

But for me that does not seem to be the case. There is always a small time lag between those. 

Could it be that the timing indicated under 'Box' in the .mat file just shows when the box starts and not the contour of the call within that box?

Best,
Isa

**Comment by DrCoffey** [comment]
You are correct, the numbers in the .xlsx are based off the contour, not the box.

**Comment by imgross** [comment]
Okay, thank you!
