### ISSUE TITLE
Screener: Error non-existent field 'windowsize'

### ISSUE THREAD

**Issue by aberz** [DrCoffey/DeepSqueak#89]
After running the call detection via the DeepSqueak-screener from UEFepilepsyAIVI, I cannot load the detected calls. The Error looks like follows:
"
Reference to non-existent field 'windowSize'.

Error in render_call_position (line 85)
     handles.CurrentCallWindowRectangle = rectangle('Position',[  handles.data.windowposition 0 handles.data.settings.windowSize  1],
     'Parent',handles.detectionAxes,'LineWidth',2,'EdgeColor','b' );

Error in loadcalls_Callback (line 100)
render_call_position(hObject,handles,true);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 34)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
"
To reproduce: 

1. Load the DeepSqueak-screener in Matlab and run the 'DeepSqueak.m' function
2. Select the audio file 'Example Rat Recording.flac' and 'Short Rat Call_V2.mat'
3. Load the detected calls 'Example Rat Recording'
4. See error above.

This happens with the provided example files as well as with my audio files.
The call detection with the 'Short Rat Call_Network_V2' and saving the files always seems to work fine. I downloaded the newest versions of DS and of the screener. Also when I try to run the original DS version everything works fine. However, since I am doing playback experiments in rats , I need to have an overview of the spectrogram to be able to distinguish between the playback and the emitted calls from the experimental rats. A colleague of mine tried analysing such files with the screener and it worked. Maybe it is machine related or something was changed in the code?

I am using Matlab 2018b on Windows 10.

I would greatly appreciate any help!

**Comment by DrCoffey** [comment]
Hey aberz,

I was not involved in coding Screener, so I can't really comment on compatibility issues. You may want to ask them if they have seen this error before. Sorry for the lack of advice.

-Kevin
