### ISSUE TITLE
Reproduceabillity

### ISSUE THREAD

**Issue by GalAvineri** [DrCoffey/DeepSqueak#90]
Hello :)
I would like to try and reproduce your results in python (while giving you all the due credit of course).
Could you please provide the means required for that?

I believe these will be necessary:
1. the raw training, test and validation datasets
2. code or comprehensive description of the following
2.1 any pre-processing done on the data
2.2. the training process
2.3. the evaluation process

**Comment by DrCoffey** [comment]
Hey Gal,

All of the information related to training is in the manuscript, and any missing details are in the code itself. We are currently using the training set to produce a new generation of networks. Collecting and curating the training set took hundreds of hours and we aren't ready to give it out just yet. We will try to share everything after our next update, but that could take some time. We are working on securing the funding to continue development currently. 

-Kevin
