### ISSUE TITLE
Missmaching time stemps

### ISSUE THREAD

**Issue by Goussha** [DrCoffey/DeepSqueak#92]
Hello,
I have encountered a phenomenon that I think should be considered.
In short, the list of calls exported excel file doesn't match the calls in the Call objects.

While the call borders in the detected Call objects are decent comparing to manual labeling, meaning each syllable is contained within a box, when looking at the calls in the exported excel sheet, there seem to be small fragments of calls rather than whole calls.

See the attached plot figure
![example](https://user-images.githubusercontent.com/60192360/89619164-2e32da00-d896-11ea-82c6-ff7def1491dc.jpg)

**Comment by DrCoffey** [comment]
Hey Goussha,

DeepSqueak is working as intended, but you are having some issues effecting the accuracy of the timestamps. 

1. DeepSqueak uses the extracted contour to calculate call onset and offset, not the box. It looks like you are only capturing the loudest part of each call. You can adjust the tonality slider on the bottom left to improve call extraction which should improve the timestamps.

2. These calls appear to be very quiet. The gaps in the signal may be tricking DeepSqueak into thinking these are more than 1 call. Using your manually segmented call 4 as an example, how do we as researchers decided that is all 1 vocalization and not 2 vocalizations closely spaced. In an ideal world you would increase the S2N of your recordings to make detection easier, but you can also try moving the sensitivity slider toward high recall. This can increase false positives, but you recordings look very clean, so it will likely just improve recall. Make sure you are detecting the full range of frequencies (20-100kHz) as well so parts of the call aren't cut off.

Let me know if that helps,
Kevin

**Comment by Goussha** [comment]
Hello Dr. Coffey,

Thank you very much for your comment.

Regarding what you said about Call#4, you are absolutely correct, 
my issue was mainly regarding the difference between the exported excel file and the boxes in the Call object,
But now I understand that by lowering the tonality threshold you can change the outcome.
And there were very few missed calls (FN) in general. All in all, this is a very impressive tool, I just wish that I had this before manually labeling literally hours of recordings.

With that in mind, and I apologize if this is not the right place to ask this,
How can accuracy, recall, and precision be calculated and compared across different models if it is possible to represent the same syllable more than once?
On one hand, if you count them as hits, this will inflate the number of TP, if you consider them as FP, this will reduce the precision, or you can just ignore them.
Maybe the best way is to segment the recordings into small fragments and label each fragment as either part of a syllable or not?
