### ISSUE TITLE
Selecting multiple calls within one spectrogram

### ISSUE THREAD

**Issue by nvd1** [DrCoffey/DeepSqueak#93]
Hi Kevin and Russell,

I'm training a new detection network with mouse calls right now, and it often puts more than one call within the same box (see image). 
<img width="178" alt="2 calls" src="https://user-images.githubusercontent.com/67161808/90086352-195ba980-dccf-11ea-9ed4-b4e1ce161091.PNG">
I know that with more training, the network will get better at separating calls. However, a feature that would enable us to draw multiple boxes within the same spectrogram would be super useful to speed up the process.

Thank you for your consideration!
Nat

**Comment by DrCoffey** [comment]
Hey Nat,

Currently, only DeepSqueak Screener can do this. https://github.com/UEFepilepsyAIVI/DeepSqueak

We are aiming to integrate this feature into the main branch soon.

-Kevin

**Comment by nvd1** [comment]
Excellent, thank you for the link!

Nat
