### ISSUE TITLE
DeepSqueak Skipping Audio Chunks

### ISSUE THREAD

**Issue by Rodent0Mimic** [DrCoffey/DeepSqueak#95]
I have tried to run several files through DeepSqueak that accidentally had an expansion factor. DeepSqueak pulls up a bunch of errors, one of which is that audio chunks are skipping. I have even tried speeding up the audio files to counteract the time expansion factor, but DeepSqueak gave me the same errors. Are there any settings I can use to still be able to run those files?

I am using Matlab R2019a and DeepSqueak 2.6.1.

**Comment by DrCoffey** [comment]
Mathworks broke all monochrome cnn detection in Matlab 2019a. Any image that is not 3 channels will throw an error. Luckily it is an easy fix. Either install 2018b, or you need to change the file permissions to edit core functions. They fixed this in 2020, but there is a separate bug they introduced. That fix is at the top of the issues section. 

Change this file:
MATLAB\R2019b\toolbox\vision\vision+vision+internal+cnn+validation\checkImageAndNetworkChannelSizes.m
From this:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3 || Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
To This:
function checkImageAndNetworkChannelSizes(I, networkChannelSize)
% If the input image size has a different channel size than that of
% the network input size, we need to error.

[~, ~, Isize] = size(I);

if ndims(I) ~= 3
if Isize ~= networkChannelSize
error(message('vision:rcnn:invalidInputImageChannelSize', Isize, networkChannelSize));
end
end

**Comment by DrCoffey** [comment]
Everything is now functional again in 2020b.

**Comment by ralphpeterson** [comment]
I am having the same issue and am looking forward to trying 2020b! I'm wondering if you know whether 2020b supports creation of network training images? (Tools->Network Training->Create Detection Network Training Images) Thanks!

**Comment by DrCoffey** [comment]
It should create images just fine, but I am not sure if the network training will work properly. The only version we can guarantee network training in is 2018a.
