### ISSUE TITLE
I cannot detect USV sound files.

### ISSUE THREAD

**Issue by sokuri0206** [DrCoffey/DeepSqueak#96]
After loading USV audio file and pressing detect,
I get Initializing matlab pop up and matlab error as below.

.
-----------------------------------------------------------------------

Error in SqueakDetect (line 57)
U = sum(hamming(wind).^2);

Error in multinetdect_Callback (line 77)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname,handles.optimization_slider.Value)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
 
Error while evaluating UIControl Callback.

.
--------------------------------------------------------------------

I'm using matlab 2020b for students, and I am not expert at matlab, sorry for that if this bug is my mistake.
Thankyou in advance.
Have a good day

**Comment by DrCoffey** [comment]
Hey, my guess is that you don't have the Signal Processing Toolbox installed. Make sure you have all of the toolboxes described in the installation section of the Wiki.

**Comment by Ahmed-Eltokhi** [comment]
I have the same error in the deapsqueak screener and I 'm sure that I downloaded the Signal processing Toolbox. I use 2021a Matlab. Here is the error

nrecognized field name "windowSize".

Error in render_call_position (line 85)
     handles.CurrentCallWindowRectangle = rectangle('Position',[  handles.data.windowposition 0
     handles.data.settings.windowSize  1], 'Parent',handles.detectionAxes,'LineWidth',2,'EdgeColor','b'
     );

Error in loadcalls_Callback (line 100)
render_call_position(hObject,handles,true);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 34)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('loadcalls_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by DrCoffey** [comment]
DeepSqueak V3 is now available on the main branch, let me know if you still have this issue with the new version.

**Comment by clarebearbradders** [comment]
I've been having the same errors, and I've just downloaded the newest version of DeepSqueak (using MatLab2020b), and now I get this:
Warning: Undefined function 'spectrogram' for input arguments of type 'double'.

Error in SqueakDetect (line 90)
        [~,fr,ti,p] = spectrogram(audio(:,1),wind,noverlap,nfft,audio_info.SampleRate,'yaxis'); % Just use the first
        audio channel

Error in multinetdect_Callback (line 80)
        Calls = [Calls;
        SqueakDetect(AudioFile,NeuralNetwork,handles.audiofiles(CurrentAudioFile).name,Settings(:,k),j,length(audioselections),networkname)];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1) 
> In SqueakDetect (line 149)
In multinetdect_Callback (line 80)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('multinetdect_Callback',hObject,eventdata,guidata(hObject),1)
In uiwait (line 81)
In images.roi.internal/ROI/draw
In drawrectangle (line 217)
In DeepSqueak>rectangle_Callback (line 420)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('rectangle_Callback',hObject,eventdata,guidata(hObject))
In uiwait (line 81)
In images.roi.internal/ROI/draw
In drawrectangle (line 217)
In DeepSqueak>rectangle_Callback (line 420)
In gui_mainfcn (line 95)
In DeepSqueak (line 29)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('rectangle_Callback',hObject,eventdata,guidata(hObject)) 
No Calls found in: Clare Day 1 T Bobba 
>>

**Comment by clarebearbradders** [comment]
Any suggestions?

**Comment by DrCoffey** [comment]
Hey Clare,

The error looks like you are missing the "spectrogram" function, which is part of the Signal Processing Toolbox.

All of the required toolboxes are listed in the Wiki here: https://github.com/DrCoffey/DeepSqueak/wiki/Installation

Make sure you install them all to get the most functionality out of DeepSqueak.

-Kevin
