### ISSUE TITLE
Denoiser different across computers

### ISSUE THREAD

**Issue by nvd1** [DrCoffey/DeepSqueak#97]
Hello!

Three computers in my lab are using DS to detect the same audio file, using the same detection network and same denoiser. All are running on Matlab 2018a. 

Two of the computers (both Windows 10, one with the newest DS update and one running on an old one) detected appox the same # of calls (575). The denoiser rejected approx the same number of calls (within 5 calls out of ~75 pieces of noise rejected, expected in our noisy audio).

However, the other computer (Mac, running the newest DS update) detected a similar number of calls, but the denoiser culled 313 of them. Most of these were true calls, not noise. We repeated the process and got the same results.

Do you have any idea as to why the same denoiser would have different effects on one computer vs another? Thank you in advance for any help.

Nat

**Comment by DrCoffey** [comment]
DeepSqueak V3 is now available on the master branch and generally doesn't require denoising. I am going to stop supporting the old version, but let me know if you still have issues with V3
