### ISSUE TITLE
Network training issue 2018a - "Unable to find any region proposals to use as positive training samples"

### ISSUE THREAD

**Issue by ralphpeterson** [DrCoffey/DeepSqueak#98]
Hi, I'm using MATLAB 2018a to train a network from scratch on Mongolian gerbil vocalizations. I have selected my training images, but get this error when training (following instructions on the wiki) -- does anyone have advice about what could be going wrong?

Thanks! 

*************************************************************************
Training a Faster R-CNN Object Detector for the following object classes:

* USV

Step 1 of 4: Training a Region Proposal Network (RPN).
Error using vision.internal.cnn.rpn.RPNRegionReader (line 170)
Unable to find any region proposals to use as positive training samples. Lower the first value of
PositiveOverlapRange to increase the number of positive region proposals.

Error in vision.internal.cnn.rpn.RPNTrainingRegionDispatcher (line 64)
                vision.internal.cnn.rpn.RPNRegionReader(...

Error in fasterRCNNObjectDetector/createRPNTrainingDispatcher (line 665)
            dispatcher = vision.internal.cnn.rpn.RPNTrainingRegionDispatcher(...

Error in fasterRCNNObjectDetector.trainRPN (line 165)
            dispatcher = createRPNTrainingDispatcher(detector, groundTruth, opts, inputSize, params);

Error in trainFasterRCNNObjectDetector (line 289)
    [stage1Detector, rpn, info] = fasterRCNNObjectDetector.trainRPN(trainingData, rpn, options(1),
    iStageOneParams(params), checkpointSaver);

Error in TrainSqueakDetector (line 61)
detector = trainFasterRCNNObjectDetector(TrainingTables, layers, options, ...

Error in trainnew_Callback (line 41)
        [detector, layers, options] = TrainSqueakDetector(TrainingTables);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 30)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('trainnew_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

**Comment by ralphpeterson** [comment]
This seems to be working now. I was selecting a bout length of 0 during the training image selection stage thinking it would limit what I thought were duplicate USVs in the training images. I didn't notice that the TTables actually index each USV in a training image with multiple USVs. So, false alarm!

**Comment by DrCoffey** [comment]
Ok, great. Sorry I didn't get to this quickly I had a grant due and was really busy.
