### ISSUE TITLE
Peak Frequency

### ISSUE THREAD

**Issue by JHoffmeister1** [DrCoffey/DeepSqueak#99]
Is there a way to obtain the frequency at the loudest point of the call? (ie, the frequency at the point in the call with the greatest power).

Thank you for considering! 
Jesse

**Comment by DrCoffey** [comment]
Not at this point. I think it would be pretty easy to modify the code in calculate_stats if you know someone with a little coding experience. The frequency along the contour and the power along the contour are both calculated so it shouldn't be too hard to add a variable. Saving it to the excel file might take a bit to figure out.

**Comment by cmlenell1** [comment]
Hello, 
I am a postdoc in the same lab as Jessie. I'm not a coder but I believe I figured out how to add peak frequency to the calculation and excel output. I wanted to put the answer here for other people who want this measure with DeepSqueak. 

Add these three lines to the "CalculateStats.m" underneath 
% Power of the call contour
stats.Power = ridgePower;


% Peak frequency of the call contour
stats.RidgeFreq = FreqScale*stats.ridgeFreq_smooth + Box(2);
stats.PeakFreq = stats.RidgeFreq(stats.Power==max(ridgePower));

Then add peak frequency to "excel_Callback.m" by changing the following lines 

exceltable = [{'ID'} {'Label'} {'Accepted'} {'Score'}  {'Begin Time (s)'} {'End Time (s)'} {'Call Length (s)'} {'Principal Frequency (kHz)'} {'Low Freq (kHz)'} {'High Freq (kHz)'} {'Delta Freq (kHz)'} {'Frequency Standard Deviation (kHz)'} {'Slope (kHz/s)'} {'Sinuosity'} {'Mean Power (dB/Hz)'} {'Tonality'} {'Peak Freq'}];

exceltable = [exceltable; {ID} {Label} {accepted} {Score} {stats.BeginTime} {stats.EndTime} {stats.DeltaTime} {stats.PrincipalFreq} {stats.LowFreq} {stats.HighFreq} {stats.DeltaFreq} {stats.stdev} {stats.Slope} {stats.Sinuosity} {stats.MaxPower} {stats.SignalToNoise} {stats.PeakFreq}];

**Comment by DrCoffey** [comment]
Nice I'll check this out and try to add it to the new screener branch.

**Comment by DrCoffey** [comment]
V3 is now available on the master branch and includes peak frequency in the output!

**Comment by cmlenell1** [comment]
Amazing! Thanks for the update!
Charles Lenell, PhD, CCC-SLP
*he/they*
